import AppKit

/// Watches the pasteboard and applies clipboards that arrive from other devices.
///
/// macOS has no notification for pasteboard changes, so this polls the change
/// counter, which is a cheap integer comparison.
@MainActor
final class ClipboardMonitor {
    private var lastCount = NSPasteboard.general.changeCount
    private var timer: Timer?
    private let onChange: (String, Bool) -> Void

    /// Pasteboard types that mean "do not copy this anywhere": password managers and
    /// other apps mark secrets and transient data with them.
    static let concealed: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
    ]

    init(onChange: @escaping (String, Bool) -> Void) {
        self.onChange = onChange
    }

    func start() {
        guard timer == nil else { return }
        // What was copied while nobody was there to send it to is not news when somebody arrives.
        lastCount = NSPasteboard.general.changeCount
        // Half a second, and the system may stretch it by as much again to run it together with other timers.
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer?.tolerance = 0.5
    }

    /// Looks at the pasteboard only while at least one device is connected: with nobody to tell, the polling is pure cost.
    func setActive(_ active: Bool) {
        if active { start() } else { stop() }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastCount else { return }
        lastCount = pasteboard.changeCount

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.concealed) else { return }
        guard let text = pasteboard.string(forType: .string), !text.isEmpty else { return }
        guard text.utf8.count <= 1_000_000 else { return }
        onChange(text, Self.looksLikeURL(text))
    }

    /// Puts text from another device on the pasteboard without echoing it back.
    func apply(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        lastCount = pasteboard.changeCount
    }

    /// Puts a secret on the pasteboard that nothing should keep: it is marked, so clipboard managers (this app's
    /// own history included) skip it, and it is not sent on to another device.
    func applyConcealed(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        pasteboard.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        pasteboard.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        lastCount = pasteboard.changeCount
    }

    static func looksLikeURL(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.contains(where: \.isWhitespace), let url = URL(string: trimmed) else { return false }
        return ["http", "https"].contains(url.scheme?.lowercased() ?? "") && url.host != nil
    }
}
