[package]
name = "tandemd"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }
dirs = "7.0.0"
hostname = "0.4.2"
qrcode = "0.14.1"
tandem-core = { version = "0.1.0", path = "../tandem-core" }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "signal", "fs", "io-util", "sync", "time", "net"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
