//! The surface Kotlin and Swift see, generated by UniFFI.
//!
//! Nothing here holds logic. It owns a tokio runtime, converts between the core's
//! types and plain records, and forwards events to the app. The names carry a
//! `Tandem` prefix so they never collide with the app's own types.

use std::sync::{Arc, Once};

use tokio::runtime::Runtime;
use tokio::sync::broadcast::error::RecvError;

use crate::engine::{DeviceInfo, Engine, EngineConfig};
use crate::events::Event;
use crate::ids::{DeviceId, Platform};
use crate::net::Route;
use crate::platform::FileStore;
use crate::proto::{
    Battery, CallActionKind, CallMsg, CallState, HotspotMsg, InputMsg, MediaKey, NetKind, NetworkStatus,
    NotifButton, NotificationAction, NotificationMsg, ShareOrigin, Status,
};
use crate::store::{DeviceSettings, SecretStore};
use crate::transfer::OutgoingFile;

#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum TandemError {
    #[error("{reason}")]
    Failed { reason: String },
    #[error("not connected to that device")]
    NotConnected,
    #[error("that device is not part of your circle")]
    NotTrusted,
    #[error("{reason}")]
    Pairing { reason: String },
}

impl From<crate::Error> for TandemError {
    fn from(err: crate::Error) -> Self {
        match err {
            crate::Error::NotConnected => TandemError::NotConnected,
            crate::Error::NotTrusted => TandemError::NotTrusted,
            crate::Error::Pairing(reason) => TandemError::Pairing { reason },
            other => TandemError::Failed { reason: other.to_string() },
        }
    }
}

// ---- Things the app implements ----------------------------------------------------

/// Receives everything the core reports. Called on a runtime thread, so it must not
/// block: post the event to the UI thread and return.
#[uniffi::export(foreign)]
pub trait TandemEventSink: Send + Sync {
    fn on_event(&self, event: TandemEvent);
}

/// Where the identity key is kept. Android wraps it with the Keystore, macOS uses the
/// Keychain.
#[uniffi::export(foreign)]
pub trait TandemVault: Send + Sync {
    /// `None` only when nothing was stored yet. Throw when the store cannot be read, so
    /// the engine stops instead of quietly making a new identity and orphaning every
    /// pairing.
    fn load(&self) -> Result<Option<Vec<u8>>, TandemError>;
    fn save(&self, secret: Vec<u8>) -> Result<(), TandemError>;
}

/// Opening files to send and placing files that arrived.
#[uniffi::export(foreign)]
pub trait TandemFiles: Send + Sync {
    /// Returns a file descriptor the core takes ownership of. Detach it on the Kotlin
    /// side (`ParcelFileDescriptor.detachFd`) so nothing else closes it.
    fn open_read(&self, source: String) -> Result<i32, TandemError>;
    /// Moves a finished download out of the private temp file and returns where it is.
    fn store_download(&self, temp_path: String, name: String, mime: String) -> Result<String, TandemError>;
}

struct VaultAdapter(Arc<dyn TandemVault>);

impl SecretStore for VaultAdapter {
    fn load(&self) -> crate::Result<Option<Vec<u8>>> {
        self.0.load().map_err(|e| crate::Error::Crypto(format!("the key store could not be read: {e}")))
    }

    fn save(&self, secret: &[u8]) -> crate::Result<()> {
        self.0
            .save(secret.to_vec())
            .map_err(|e| crate::Error::Crypto(format!("the key store could not be written: {e}")))
    }
}

struct FilesAdapter(Arc<dyn TandemFiles>);

impl FileStore for FilesAdapter {
    fn open_read(&self, source: &str) -> std::io::Result<std::fs::File> {
        use std::os::fd::FromRawFd;
        let fd = self
            .0
            .open_read(source.to_string())
            .map_err(|e| std::io::Error::other(e.to_string()))?;
        // The app detached the descriptor, so the file is ours to close.
        Ok(unsafe { std::fs::File::from_raw_fd(fd) })
    }

    fn store_download(&self, temp: &std::path::Path, name: &str, mime: &str) -> std::io::Result<String> {
        self.0
            .store_download(temp.to_string_lossy().into_owned(), name.to_string(), mime.to_string())
            .map_err(|e| std::io::Error::other(e.to_string()))
    }
}

// ---- Plain types ------------------------------------------------------------------

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemPlatform {
    Android,
    MacOs,
    Linux,
    Windows,
    Ios,
    Other,
}

impl From<Platform> for TandemPlatform {
    fn from(p: Platform) -> Self {
        match p {
            Platform::Android => TandemPlatform::Android,
            Platform::MacOs => TandemPlatform::MacOs,
            Platform::Linux => TandemPlatform::Linux,
            Platform::Windows => TandemPlatform::Windows,
            Platform::Ios => TandemPlatform::Ios,
            Platform::Other => TandemPlatform::Other,
        }
    }
}

impl From<TandemPlatform> for Platform {
    fn from(p: TandemPlatform) -> Self {
        match p {
            TandemPlatform::Android => Platform::Android,
            TandemPlatform::MacOs => Platform::MacOs,
            TandemPlatform::Linux => Platform::Linux,
            TandemPlatform::Windows => Platform::Windows,
            TandemPlatform::Ios => Platform::Ios,
            TandemPlatform::Other => Platform::Other,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemRoute {
    Lan,
    Tailnet,
    Other,
}

impl From<Route> for TandemRoute {
    fn from(r: Route) -> Self {
        match r {
            Route::Lan => TandemRoute::Lan,
            Route::Tailnet => TandemRoute::Tailnet,
            Route::Other => TandemRoute::Other,
        }
    }
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemConfig {
    pub data_dir: String,
    pub device_name: String,
    pub platform: TandemPlatform,
    pub model: Option<String>,
    pub app_version: String,
    /// Zero picks a port. The default (47820) is tried first when this is 47820.
    pub port: u16,
    pub enable_mdns: bool,
    pub caps: Vec<String>,
    /// Longer keep-alives for a phone that is idle, to spare the battery.
    pub low_power: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemNetKind {
    None,
    Wifi,
    Cellular,
    Ethernet,
    Other,
}

impl From<NetKind> for TandemNetKind {
    fn from(k: NetKind) -> Self {
        match k {
            NetKind::None => TandemNetKind::None,
            NetKind::Wifi => TandemNetKind::Wifi,
            NetKind::Cellular => TandemNetKind::Cellular,
            NetKind::Ethernet => TandemNetKind::Ethernet,
            NetKind::Other => TandemNetKind::Other,
        }
    }
}

impl From<TandemNetKind> for NetKind {
    fn from(k: TandemNetKind) -> Self {
        match k {
            TandemNetKind::None => NetKind::None,
            TandemNetKind::Wifi => NetKind::Wifi,
            TandemNetKind::Cellular => NetKind::Cellular,
            TandemNetKind::Ethernet => NetKind::Ethernet,
            TandemNetKind::Other => NetKind::Other,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Record)]
pub struct TandemBattery {
    pub level: u8,
    pub charging: bool,
    pub power_save: bool,
}

#[derive(Clone, Debug, PartialEq, Eq, uniffi::Record)]
pub struct TandemNetwork {
    pub kind: TandemNetKind,
    pub ssid: Option<String>,
    pub metered: bool,
    pub roaming: bool,
    pub signal: Option<u8>,
}

/// A device's vitals. Send only what changed.
#[derive(Clone, Debug, Default, PartialEq, Eq, uniffi::Record)]
pub struct TandemStatus {
    pub battery: Option<TandemBattery>,
    pub network: Option<TandemNetwork>,
    pub hotspot: Option<bool>,
    pub dnd: Option<bool>,
    pub locked: Option<bool>,
    pub free_storage: Option<u64>,
}

impl From<Status> for TandemStatus {
    fn from(s: Status) -> Self {
        TandemStatus {
            battery: s.battery.map(|b| TandemBattery { level: b.level, charging: b.charging, power_save: b.power_save }),
            network: s.network.map(|n| TandemNetwork {
                kind: n.kind.into(),
                ssid: n.ssid,
                metered: n.metered,
                roaming: n.roaming,
                signal: n.signal,
            }),
            hotspot: s.hotspot,
            dnd: s.dnd,
            locked: s.locked,
            free_storage: s.free_storage,
        }
    }
}

impl From<TandemStatus> for Status {
    fn from(s: TandemStatus) -> Self {
        Status {
            battery: s.battery.map(|b| Battery { level: b.level, charging: b.charging, power_save: b.power_save }),
            network: s.network.map(|n| NetworkStatus {
                kind: n.kind.into(),
                ssid: n.ssid,
                metered: n.metered,
                roaming: n.roaming,
                signal: n.signal,
            }),
            hotspot: s.hotspot,
            dnd: s.dnd,
            locked: s.locked,
            free_storage: s.free_storage,
        }
    }
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemDevice {
    pub id: String,
    pub name: String,
    pub platform: TandemPlatform,
    pub online: bool,
    pub route: Option<TandemRoute>,
    pub rtt_ms: Option<u32>,
    pub status: TandemStatus,
    pub app_version: Option<String>,
    pub caps: Vec<String>,
    pub vouched_by_removed: bool,
    pub clipboard_enabled: bool,
    pub auto_accept: bool,
    pub notifications_enabled: bool,
}

impl From<DeviceInfo> for TandemDevice {
    fn from(d: DeviceInfo) -> Self {
        TandemDevice {
            id: d.id.to_string(),
            name: d.name,
            platform: d.platform.into(),
            online: d.online,
            route: d.route.map(Into::into),
            rtt_ms: d.rtt_ms,
            status: d.status.into(),
            app_version: d.app_version,
            caps: d.caps,
            vouched_by_removed: d.vouched_by_removed,
            clipboard_enabled: d.settings.clipboard,
            auto_accept: d.settings.auto_accept,
            notifications_enabled: d.settings.notifications,
        }
    }
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemPairingOffer {
    pub uri: String,
    pub expires_at_ms: u64,
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemOutgoingFile {
    pub source: String,
    pub name: String,
    /// Zero means "look it up".
    pub size: u64,
    pub mime: String,
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemSendReport {
    pub offer: u64,
    pub sent_to: Vec<String>,
    pub offline: Vec<String>,
}

#[derive(Clone, Copy, Debug, uniffi::Enum)]
pub enum TandemShareOrigin {
    Files,
    Screenshot,
    Photo,
    Clipboard,
    Other,
}

impl From<TandemShareOrigin> for ShareOrigin {
    fn from(o: TandemShareOrigin) -> Self {
        match o {
            TandemShareOrigin::Files => ShareOrigin::Files,
            TandemShareOrigin::Screenshot => ShareOrigin::Screenshot,
            TandemShareOrigin::Photo => ShareOrigin::Photo,
            TandemShareOrigin::Clipboard => ShareOrigin::Clipboard,
            TandemShareOrigin::Other => ShareOrigin::Other,
        }
    }
}

impl From<ShareOrigin> for TandemShareOrigin {
    fn from(o: ShareOrigin) -> Self {
        match o {
            ShareOrigin::Files => TandemShareOrigin::Files,
            ShareOrigin::Screenshot => TandemShareOrigin::Screenshot,
            ShareOrigin::Photo => TandemShareOrigin::Photo,
            ShareOrigin::Clipboard => TandemShareOrigin::Clipboard,
            ShareOrigin::Other => TandemShareOrigin::Other,
        }
    }
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemShareItem {
    pub name: String,
    pub size: u64,
    pub mime: String,
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemButton {
    pub id: String,
    pub title: String,
    pub is_reply: bool,
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemNotification {
    pub key: String,
    pub app_id: String,
    pub app_name: String,
    pub title: String,
    pub text: String,
    pub sub_text: Option<String>,
    pub ts: u64,
    pub ongoing: bool,
    pub silent: bool,
    pub buttons: Vec<TandemButton>,
    pub otp: Option<String>,
    pub progress_done: Option<u32>,
    pub progress_total: Option<u32>,
}

impl From<NotificationMsg> for TandemNotification {
    fn from(n: NotificationMsg) -> Self {
        TandemNotification {
            key: n.key,
            app_id: n.app_id,
            app_name: n.app_name,
            title: n.title,
            text: n.text,
            sub_text: n.sub_text,
            ts: n.ts,
            ongoing: n.ongoing,
            silent: n.silent,
            buttons: n
                .buttons
                .into_iter()
                .map(|b| TandemButton { id: b.id, title: b.title, is_reply: b.is_reply })
                .collect(),
            otp: n.otp,
            progress_done: n.progress.map(|p| p.0),
            progress_total: n.progress.map(|p| p.1),
        }
    }
}

impl From<TandemNotification> for NotificationMsg {
    fn from(n: TandemNotification) -> Self {
        NotificationMsg {
            key: n.key,
            app_id: n.app_id,
            app_name: n.app_name,
            title: n.title,
            text: n.text,
            sub_text: n.sub_text,
            ts: n.ts,
            ongoing: n.ongoing,
            silent: n.silent,
            buttons: n
                .buttons
                .into_iter()
                .map(|b| NotifButton { id: b.id, title: b.title, is_reply: b.is_reply })
                .collect(),
            otp: n.otp,
            progress: match (n.progress_done, n.progress_total) {
                (Some(done), Some(total)) => Some((done, total)),
                _ => None,
            },
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemCallState {
    Ringing,
    Dialing,
    Active,
    Ended,
    Missed,
}

impl From<CallState> for TandemCallState {
    fn from(s: CallState) -> Self {
        match s {
            CallState::Ringing => TandemCallState::Ringing,
            CallState::Dialing => TandemCallState::Dialing,
            CallState::Active => TandemCallState::Active,
            CallState::Ended => TandemCallState::Ended,
            CallState::Missed => TandemCallState::Missed,
        }
    }
}

impl From<TandemCallState> for CallState {
    fn from(s: TandemCallState) -> Self {
        match s {
            TandemCallState::Ringing => CallState::Ringing,
            TandemCallState::Dialing => CallState::Dialing,
            TandemCallState::Active => CallState::Active,
            TandemCallState::Ended => CallState::Ended,
            TandemCallState::Missed => CallState::Missed,
        }
    }
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemCall {
    pub id: String,
    pub state: TandemCallState,
    pub incoming: bool,
    pub number: Option<String>,
    pub name: Option<String>,
    pub ts: u64,
}

#[derive(Clone, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemCallAction {
    Answer,
    Reject,
    Silence,
    Hangup,
    RejectWithMessage { message: String },
}

impl From<CallActionKind> for TandemCallAction {
    fn from(a: CallActionKind) -> Self {
        match a {
            CallActionKind::Answer => TandemCallAction::Answer,
            CallActionKind::Reject => TandemCallAction::Reject,
            CallActionKind::Silence => TandemCallAction::Silence,
            CallActionKind::Hangup => TandemCallAction::Hangup,
            CallActionKind::RejectWithMessage(message) => TandemCallAction::RejectWithMessage { message },
        }
    }
}

impl From<TandemCallAction> for CallActionKind {
    fn from(a: TandemCallAction) -> Self {
        match a {
            TandemCallAction::Answer => CallActionKind::Answer,
            TandemCallAction::Reject => CallActionKind::Reject,
            TandemCallAction::Silence => CallActionKind::Silence,
            TandemCallAction::Hangup => CallActionKind::Hangup,
            TandemCallAction::RejectWithMessage { message } => CallActionKind::RejectWithMessage(message),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemMediaKey {
    PlayPause,
    Next,
    Previous,
    VolumeUp,
    VolumeDown,
    Mute,
}

impl From<MediaKey> for TandemMediaKey {
    fn from(k: MediaKey) -> Self {
        match k {
            MediaKey::PlayPause => TandemMediaKey::PlayPause,
            MediaKey::Next => TandemMediaKey::Next,
            MediaKey::Previous => TandemMediaKey::Previous,
            MediaKey::VolumeUp => TandemMediaKey::VolumeUp,
            MediaKey::VolumeDown => TandemMediaKey::VolumeDown,
            MediaKey::Mute => TandemMediaKey::Mute,
        }
    }
}

impl From<TandemMediaKey> for MediaKey {
    fn from(k: TandemMediaKey) -> Self {
        match k {
            TandemMediaKey::PlayPause => MediaKey::PlayPause,
            TandemMediaKey::Next => MediaKey::Next,
            TandemMediaKey::Previous => MediaKey::Previous,
            TandemMediaKey::VolumeUp => MediaKey::VolumeUp,
            TandemMediaKey::VolumeDown => MediaKey::VolumeDown,
            TandemMediaKey::Mute => MediaKey::Mute,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemInput {
    Pointer { dx: i16, dy: i16 },
    Scroll { dx: i16, dy: i16 },
    Button { button: u8, down: bool },
    Click { button: u8, count: u8 },
    Key { code: u16, down: bool, mods: u8 },
    Text { text: String },
    Media { key: TandemMediaKey },
}

impl From<InputMsg> for TandemInput {
    fn from(i: InputMsg) -> Self {
        match i {
            InputMsg::Pointer { dx, dy } => TandemInput::Pointer { dx, dy },
            InputMsg::Scroll { dx, dy } => TandemInput::Scroll { dx, dy },
            InputMsg::Button { button, down } => TandemInput::Button { button, down },
            InputMsg::Click { button, count } => TandemInput::Click { button, count },
            InputMsg::Key { code, down, mods } => TandemInput::Key { code, down, mods },
            InputMsg::Text(text) => TandemInput::Text { text },
            InputMsg::Media(key) => TandemInput::Media { key: key.into() },
        }
    }
}

impl From<TandemInput> for InputMsg {
    fn from(i: TandemInput) -> Self {
        match i {
            TandemInput::Pointer { dx, dy } => InputMsg::Pointer { dx, dy },
            TandemInput::Scroll { dx, dy } => InputMsg::Scroll { dx, dy },
            TandemInput::Button { button, down } => InputMsg::Button { button, down },
            TandemInput::Click { button, count } => InputMsg::Click { button, count },
            TandemInput::Key { code, down, mods } => InputMsg::Key { code, down, mods },
            TandemInput::Text { text } => InputMsg::Text(text),
            TandemInput::Media { key } => InputMsg::Media(key.into()),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemHotspot {
    Request { reason: String },
    State { on: bool, ssid: Option<String>, clients: u8, data_used: Option<u64>, error: Option<String> },
    Stop,
}

impl From<HotspotMsg> for TandemHotspot {
    fn from(h: HotspotMsg) -> Self {
        match h {
            HotspotMsg::Request { reason } => TandemHotspot::Request { reason },
            HotspotMsg::State { on, ssid, clients, data_used, error } => {
                TandemHotspot::State { on, ssid, clients, data_used, error }
            }
            HotspotMsg::Stop => TandemHotspot::Stop,
        }
    }
}

impl From<TandemHotspot> for HotspotMsg {
    fn from(h: TandemHotspot) -> Self {
        match h {
            TandemHotspot::Request { reason } => HotspotMsg::Request { reason },
            TandemHotspot::State { on, ssid, clients, data_used, error } => {
                HotspotMsg::State { on, ssid, clients, data_used, error }
            }
            TandemHotspot::Stop => HotspotMsg::Stop,
        }
    }
}

#[derive(Clone, Debug, uniffi::Enum)]
pub enum TandemEvent {
    DevicesChanged,
    Connected { id: String },
    Disconnected { id: String },
    Paired { id: String },
    CircleChanged,
    RemovedFromCircle,
    Clipboard { from: String, text: String, is_url: bool },
    ShareOffered { from: String, offer: u64, origin: TandemShareOrigin, items: Vec<TandemShareItem> },
    ShareText { from: String, text: String, is_url: bool, open: bool },
    Progress { offer: u64, index: u32, peer: String, incoming: bool, name: String, done: u64, total: u64 },
    Finished {
        offer: u64,
        index: u32,
        peer: String,
        incoming: bool,
        name: String,
        size: u64,
        location: Option<String>,
        error: Option<String>,
    },
    Notification { from: String, notification: TandemNotification },
    NotificationRemoved { from: String, key: String },
    NotificationAction { from: String, key: String, button: String, reply: Option<String>, dismiss: bool },
    AppIcon { from: String, app_id: String, png: Vec<u8> },
    Call { from: String, call: TandemCall },
    CallAction { from: String, id: String, action: TandemCallAction },
    Dial { from: String, number: String },
    Ring { from: String, on: bool },
    Input { from: String, input: TandemInput },
    Hotspot { from: String, hotspot: TandemHotspot },
}

impl From<Event> for TandemEvent {
    fn from(event: Event) -> Self {
        match event {
            Event::DevicesChanged => TandemEvent::DevicesChanged,
            Event::Connected { id } => TandemEvent::Connected { id: id.to_string() },
            Event::Disconnected { id } => TandemEvent::Disconnected { id: id.to_string() },
            Event::Paired { id } => TandemEvent::Paired { id: id.to_string() },
            Event::CircleChanged => TandemEvent::CircleChanged,
            Event::RemovedFromCircle => TandemEvent::RemovedFromCircle,
            Event::Clipboard { from, text, is_url } => TandemEvent::Clipboard { from: from.to_string(), text, is_url },
            Event::ShareOffered { from, offer } => TandemEvent::ShareOffered {
                from: from.to_string(),
                offer: offer.id,
                origin: offer.origin.into(),
                items: offer
                    .items
                    .into_iter()
                    .map(|i| TandemShareItem { name: i.name, size: i.size, mime: i.mime })
                    .collect(),
            },
            Event::ShareText { from, text, is_url, open } => {
                TandemEvent::ShareText { from: from.to_string(), text, is_url, open }
            }
            Event::Progress(p) => TandemEvent::Progress {
                offer: p.offer,
                index: p.index,
                peer: p.peer.to_string(),
                incoming: p.incoming,
                name: p.name,
                done: p.done,
                total: p.total,
            },
            Event::Finished(d) => TandemEvent::Finished {
                offer: d.offer,
                index: d.index,
                peer: d.peer.to_string(),
                incoming: d.incoming,
                name: d.name,
                size: d.size,
                location: d.location,
                error: d.error,
            },
            Event::Notification { from, notification } => {
                TandemEvent::Notification { from: from.to_string(), notification: notification.into() }
            }
            Event::NotificationRemoved { from, key } => TandemEvent::NotificationRemoved { from: from.to_string(), key },
            Event::NotificationAction { from, action } => TandemEvent::NotificationAction {
                from: from.to_string(),
                key: action.key,
                button: action.button,
                reply: action.reply,
                dismiss: action.dismiss,
            },
            Event::AppIcon { from, app_id, png } => TandemEvent::AppIcon { from: from.to_string(), app_id, png },
            Event::Call { from, call } => TandemEvent::Call {
                from: from.to_string(),
                call: TandemCall {
                    id: call.id,
                    state: call.state.into(),
                    incoming: call.incoming,
                    number: call.number,
                    name: call.name,
                    ts: call.ts,
                },
            },
            Event::CallAction { from, action } => {
                TandemEvent::CallAction { from: from.to_string(), id: action.id, action: action.action.into() }
            }
            Event::Dial { from, number } => TandemEvent::Dial { from: from.to_string(), number },
            Event::Ring { from, on } => TandemEvent::Ring { from: from.to_string(), on },
            Event::Input { from, input } => TandemEvent::Input { from: from.to_string(), input: input.into() },
            Event::Hotspot { from, hotspot } => TandemEvent::Hotspot { from: from.to_string(), hotspot: hotspot.into() },
        }
    }
}

// ---- Logging ----------------------------------------------------------------------

static LOGGING: Once = Once::new();

/// Routes the core's logs to the platform log (logcat on Android, the unified log on
/// Apple systems). Safe to call more than once.
#[uniffi::export]
pub fn tandem_init_logging(verbose: bool) {
    LOGGING.call_once(|| {
        let level = if verbose { log::LevelFilter::Debug } else { log::LevelFilter::Info };
        #[cfg(target_os = "android")]
        android_logger::init_once(android_logger::Config::default().with_max_level(level).with_tag("Tandem"));
        #[cfg(target_vendor = "apple")]
        {
            let _ = oslog::OsLogger::new("nl.markmaaktmedia.Tandem").level_filter(level).init();
        }
        #[cfg(not(any(target_os = "android", target_vendor = "apple")))]
        let _ = level;
    });
}

// ---- The engine -------------------------------------------------------------------

/// Owns the runtime and shuts it down without blocking, so dropping the engine from
/// any thread (including one that belongs to another runtime) is safe.
struct OwnedRuntime(Option<Runtime>);

impl std::ops::Deref for OwnedRuntime {
    type Target = Runtime;

    fn deref(&self) -> &Runtime {
        self.0.as_ref().expect("runtime is alive until drop")
    }
}

impl Drop for OwnedRuntime {
    fn drop(&mut self) {
        if let Some(runtime) = self.0.take() {
            runtime.shutdown_background();
        }
    }
}

#[derive(uniffi::Object)]
pub struct TandemEngine {
    runtime: OwnedRuntime,
    engine: Engine,
}

fn parse_ids(ids: &[String]) -> Result<Vec<DeviceId>, TandemError> {
    ids.iter()
        .map(|id| DeviceId::parse(id).map_err(TandemError::from))
        .collect()
}

fn ids_to_strings(ids: Vec<DeviceId>) -> Vec<String> {
    ids.into_iter().map(|id| id.to_string()).collect()
}

#[uniffi::export(async_runtime = "tokio")]
impl TandemEngine {
    /// Starts the engine. Call it from a background thread: it opens the socket and
    /// announces on the network.
    #[uniffi::constructor]
    pub fn start(
        config: TandemConfig,
        vault: Arc<dyn TandemVault>,
        files: Arc<dyn TandemFiles>,
        sink: Arc<dyn TandemEventSink>,
    ) -> Result<Arc<TandemEngine>, TandemError> {
        let runtime = tokio::runtime::Builder::new_multi_thread()
            .worker_threads(2)
            .thread_name("tandem")
            .enable_all()
            .build()
            .map_err(|e| TandemError::Failed { reason: e.to_string() })?;

        let mut cfg = EngineConfig::new(&config.data_dir, &config.device_name);
        cfg.platform = config.platform.into();
        cfg.model = config.model;
        cfg.app_version = config.app_version;
        cfg.port = config.port;
        cfg.enable_mdns = config.enable_mdns;
        cfg.caps = config.caps;
        if config.low_power {
            cfg.tuning.keep_alive = std::time::Duration::from_secs(25);
            cfg.tuning.idle_timeout = std::time::Duration::from_secs(70);
        }

        let engine = runtime
            .block_on(Engine::start(cfg, Arc::new(VaultAdapter(vault)), Arc::new(FilesAdapter(files))))
            .map_err(TandemError::from)?;

        let mut events = engine.subscribe();
        runtime.spawn(async move {
            loop {
                match events.recv().await {
                    Ok(event) => sink.on_event(event.into()),
                    Err(RecvError::Lagged(missed)) => {
                        tracing::warn!("the app fell behind by {missed} events");
                        sink.on_event(TandemEvent::DevicesChanged);
                    }
                    Err(RecvError::Closed) => break,
                }
            }
        });

        Ok(Arc::new(TandemEngine { runtime: OwnedRuntime(Some(runtime)), engine }))
    }

    pub fn id(&self) -> String {
        self.engine.id().to_string()
    }

    pub fn name(&self) -> String {
        self.engine.name()
    }

    pub fn port(&self) -> u16 {
        self.engine.port()
    }

    pub fn devices(&self) -> Vec<TandemDevice> {
        self.engine.devices().into_iter().map(Into::into).collect()
    }

    pub fn is_member(&self) -> bool {
        self.engine.is_member()
    }

    /// Call when Wi-Fi, mobile data or the VPN changed.
    pub fn network_changed(&self) {
        let _guard = self.runtime.enter();
        self.engine.network_changed();
    }

    pub fn create_pairing_offer(&self) -> Result<TandemPairingOffer, TandemError> {
        let offer = self.engine.create_pairing_offer()?;
        Ok(TandemPairingOffer { uri: offer.uri, expires_at_ms: offer.expires_at })
    }

    pub fn cancel_pairing_offer(&self) {
        self.engine.cancel_pairing_offer();
    }

    pub fn set_device_settings(
        &self,
        id: String,
        clipboard: bool,
        auto_accept: bool,
        notifications: bool,
    ) -> Result<(), TandemError> {
        let id = DeviceId::parse(&id)?;
        self.engine
            .set_device_settings(&id, DeviceSettings { clipboard, auto_accept, notifications })
            .map_err(Into::into)
    }

    pub fn accept_offer(&self, from: String, offer: u64) -> Result<(), TandemError> {
        let _guard = self.runtime.enter();
        self.engine.accept_offer(DeviceId::parse(&from)?, offer).map_err(Into::into)
    }

    pub fn is_connected(&self, id: String) -> bool {
        DeviceId::parse(&id).map(|id| self.engine.is_connected(&id)).unwrap_or(false)
    }

    /// Sends a pointer movement without waiting for delivery.
    pub fn send_pointer(&self, id: String, dx: i16, dy: i16) -> Result<(), TandemError> {
        let id = DeviceId::parse(&id)?;
        self.engine.send_datagram(&id, crate::session::pointer_datagram(dx, dy)).map_err(Into::into)
    }

    pub fn send_scroll(&self, id: String, dx: i16, dy: i16) -> Result<(), TandemError> {
        let id = DeviceId::parse(&id)?;
        self.engine.send_datagram(&id, crate::session::scroll_datagram(dx, dy)).map_err(Into::into)
    }

    pub async fn pair_with_uri(&self, uri: String) -> Result<String, TandemError> {
        let engine = self.engine.clone();
        let id = self
            .runtime
            .spawn(async move { engine.pair_with_uri(&uri).await })
            .await
            .map_err(join_error)??;
        Ok(id.to_string())
    }

    pub async fn remove_device(&self, id: String) -> Result<(), TandemError> {
        let id = DeviceId::parse(&id)?;
        let engine = self.engine.clone();
        self.runtime.spawn(async move { engine.remove_device(id).await }).await.map_err(join_error)??;
        Ok(())
    }

    pub async fn rename_self(&self, name: String) -> Result<(), TandemError> {
        let engine = self.engine.clone();
        self.runtime.spawn(async move { engine.rename_self(&name).await }).await.map_err(join_error)??;
        Ok(())
    }

    pub async fn send_files(
        &self,
        targets: Vec<String>,
        files: Vec<TandemOutgoingFile>,
        origin: TandemShareOrigin,
    ) -> Result<TandemSendReport, TandemError> {
        let targets = parse_ids(&targets)?;
        let files: Vec<OutgoingFile> = files
            .into_iter()
            .map(|f| OutgoingFile { source: f.source, name: f.name, size: f.size, mime: f.mime })
            .collect();
        let engine = self.engine.clone();
        let report = self
            .runtime
            .spawn(async move { engine.send_files(&targets, files, origin.into()).await })
            .await
            .map_err(join_error)??;
        Ok(TandemSendReport {
            offer: report.offer,
            sent_to: ids_to_strings(report.sent_to),
            offline: ids_to_strings(report.offline),
        })
    }

    pub async fn send_bytes(
        &self,
        targets: Vec<String>,
        name: String,
        mime: String,
        data: Vec<u8>,
        origin: TandemShareOrigin,
    ) -> Result<TandemSendReport, TandemError> {
        let targets = parse_ids(&targets)?;
        let engine = self.engine.clone();
        let report = self
            .runtime
            .spawn(async move { engine.send_bytes(&targets, &name, &mime, data, origin.into()).await })
            .await
            .map_err(join_error)??;
        Ok(TandemSendReport {
            offer: report.offer,
            sent_to: ids_to_strings(report.sent_to),
            offline: ids_to_strings(report.offline),
        })
    }

    pub async fn send_text(
        &self,
        targets: Vec<String>,
        text: String,
        is_url: bool,
        open: bool,
    ) -> Result<Vec<String>, TandemError> {
        let targets = parse_ids(&targets)?;
        let engine = self.engine.clone();
        let reached = self
            .runtime
            .spawn(async move { engine.send_text(&targets, &text, is_url, open).await })
            .await
            .map_err(join_error)?;
        Ok(ids_to_strings(reached))
    }

    pub async fn clipboard_changed(&self, text: String, is_url: bool) {
        let engine = self.engine.clone();
        let _ = self.runtime.spawn(async move { engine.clipboard_changed(&text, is_url).await }).await;
    }

    pub async fn send_clipboard(
        &self,
        targets: Vec<String>,
        text: String,
        is_url: bool,
    ) -> Result<Vec<String>, TandemError> {
        let targets = parse_ids(&targets)?;
        let engine = self.engine.clone();
        let reached = self
            .runtime
            .spawn(async move { engine.send_clipboard(&targets, &text, is_url).await })
            .await
            .map_err(join_error)?;
        Ok(ids_to_strings(reached))
    }

    pub async fn update_status(&self, status: TandemStatus) {
        let engine = self.engine.clone();
        let _ = self.runtime.spawn(async move { engine.update_status(status.into()).await }).await;
    }

    pub async fn send_notification(
        &self,
        targets: Vec<String>,
        notification: TandemNotification,
    ) -> Result<Vec<String>, TandemError> {
        self.send(targets, crate::proto::Msg::Notification(notification.into())).await
    }

    pub async fn remove_notification(&self, targets: Vec<String>, key: String) -> Result<Vec<String>, TandemError> {
        self.send(targets, crate::proto::Msg::NotificationRemoved { key }).await
    }

    pub async fn notification_action(
        &self,
        target: String,
        key: String,
        button: String,
        reply: Option<String>,
        dismiss: bool,
    ) -> Result<(), TandemError> {
        let msg = crate::proto::Msg::NotificationAction(NotificationAction { key, button, reply, dismiss });
        self.send(vec![target], msg).await.map(|_| ())
    }

    pub async fn send_app_icon(&self, targets: Vec<String>, app_id: String, png: Vec<u8>) -> Result<Vec<String>, TandemError> {
        self.send(targets, crate::proto::Msg::AppIcon { app_id, png: crate::proto::bytes(png) }).await
    }

    pub async fn send_call(&self, targets: Vec<String>, call: TandemCall) -> Result<Vec<String>, TandemError> {
        let msg = crate::proto::Msg::Call(CallMsg {
            id: call.id,
            state: call.state.into(),
            incoming: call.incoming,
            number: call.number,
            name: call.name,
            ts: call.ts,
        });
        self.send(targets, msg).await
    }

    pub async fn call_action(&self, target: String, id: String, action: TandemCallAction) -> Result<(), TandemError> {
        let msg = crate::proto::Msg::CallAction(crate::proto::CallAction { id, action: action.into() });
        self.send(vec![target], msg).await.map(|_| ())
    }

    pub async fn dial(&self, target: String, number: String) -> Result<(), TandemError> {
        self.send(vec![target], crate::proto::Msg::Dial { number }).await.map(|_| ())
    }

    pub async fn ring(&self, target: String, on: bool) -> Result<(), TandemError> {
        self.send(vec![target], crate::proto::Msg::Ring { on }).await.map(|_| ())
    }

    pub async fn send_input(&self, target: String, input: TandemInput) -> Result<(), TandemError> {
        self.send(vec![target], crate::proto::Msg::Input(input.into())).await.map(|_| ())
    }

    pub async fn send_hotspot(&self, target: String, hotspot: TandemHotspot) -> Result<(), TandemError> {
        self.send(vec![target], crate::proto::Msg::Hotspot(hotspot.into())).await.map(|_| ())
    }

    pub async fn decline_offer(&self, from: String, offer: u64) -> Result<(), TandemError> {
        let from = DeviceId::parse(&from)?;
        let engine = self.engine.clone();
        self.runtime.spawn(async move { engine.decline_offer(from, offer).await }).await.map_err(join_error)?;
        Ok(())
    }

    pub async fn shutdown(&self) {
        let engine = self.engine.clone();
        let _ = self.runtime.spawn(async move { engine.shutdown().await }).await;
    }
}

impl TandemEngine {
    async fn send(&self, targets: Vec<String>, msg: crate::proto::Msg) -> Result<Vec<String>, TandemError> {
        let targets = parse_ids(&targets)?;
        let wanted = targets.len();
        let engine = self.engine.clone();
        let reached = self
            .runtime
            .spawn(async move { engine.send_msg(&targets, msg).await })
            .await
            .map_err(join_error)?;
        if reached.is_empty() && wanted > 0 {
            return Err(TandemError::NotConnected);
        }
        Ok(ids_to_strings(reached))
    }
}

fn join_error(e: tokio::task::JoinError) -> TandemError {
    TandemError::Failed { reason: format!("internal error: {e}") }
}
