//! The surface Kotlin and Swift see, generated by UniFFI.
//!
//! Nothing here holds logic. It owns a tokio runtime, converts between the core's
//! types and plain records, and forwards events to the app. The names carry a
//! `Tandem` prefix so they never collide with the app's own types.

use std::sync::{Arc, Once};

use tokio::runtime::Runtime;
use tokio::sync::broadcast::error::RecvError;

use crate::engine::{DeviceInfo, Engine, EngineConfig};
use crate::events::Event;
use crate::ids::{DeviceId, Platform};
use crate::net::Route;
use crate::platform::FileStore;
use crate::proto::{
    Battery, CallActionKind, CallMsg, CallState, CaptureKind, CaptureWhy, HotspotMsg, InputMsg, MediaKey, NetKind, NetworkStatus,
    NotifButton, NotificationAction, NotificationMsg, ShareOrigin, Status,
};
use crate::store::{DeviceSettings, SecretStore};
use crate::transfer::OutgoingFile;

#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum TandemError {
    #[error("{reason}")]
    Failed { reason: String },
    #[error("not connected to that device")]
    NotConnected,
    #[error("that device is not part of your circle")]
    NotTrusted,
    #[error("{reason}")]
    Pairing { reason: String },
    /// The other device would not do what was asked with its files. `code` is one of: not_found, denied, disabled,
    /// outside, exists, not_empty, not_dir, is_dir, too_large, unsupported, io.
    #[error("{reason}")]
    Files { code: String, reason: String },
}

impl From<crate::Error> for TandemError {
    fn from(err: crate::Error) -> Self {
        match err {
            crate::Error::NotConnected => TandemError::NotConnected,
            crate::Error::NotTrusted => TandemError::NotTrusted,
            crate::Error::Pairing(reason) => TandemError::Pairing { reason },
            crate::Error::Files { code, message } => TandemError::Files { code: code.as_str().to_string(), reason: message },
            other => TandemError::Failed { reason: other.to_string() },
        }
    }
}

// ---- Things the app implements ----------------------------------------------------

/// Receives everything the core reports. Called on a runtime thread, so it must not
/// block: post the event to the UI thread and return.
#[uniffi::export(foreign)]
pub trait TandemEventSink: Send + Sync {
    fn on_event(&self, event: TandemEvent);
}

/// Receives the sound another device sends. Called on the connection's own task for every packet,
/// so it must only queue the samples and return, never wait for the speaker.
#[uniffi::export(foreign)]
pub trait TandemAudioSink: Send + Sync {
    fn on_audio(&self, from: String, stream: u8, seq: u32, pcm: Vec<u8>);
}

struct AudioAdapter(Arc<dyn TandemAudioSink>);

impl crate::engine::AudioSink for AudioAdapter {
    fn audio(&self, from: DeviceId, stream: u8, seq: u32, pcm: &[u8]) {
        self.0.on_audio(from.to_string(), stream, seq, pcm.to_vec());
    }
}

/// Where the identity key is kept. Android wraps it with the Keystore, macOS uses the
/// Keychain.
#[uniffi::export(foreign)]
pub trait TandemVault: Send + Sync {
    /// `None` only when nothing was stored yet. Throw when the store cannot be read, so
    /// the engine stops instead of quietly making a new identity and orphaning every
    /// pairing.
    fn load(&self) -> Result<Option<Vec<u8>>, TandemError>;
    fn save(&self, secret: Vec<u8>) -> Result<(), TandemError>;
}

/// Opening files to send and placing files that arrived.
#[uniffi::export(foreign)]
pub trait TandemFiles: Send + Sync {
    /// Returns a file descriptor the core takes ownership of. Detach it on the Kotlin
    /// side (`ParcelFileDescriptor.detachFd`) so nothing else closes it.
    fn open_read(&self, source: String) -> Result<i32, TandemError>;
    /// Moves a finished download out of the private temp file and returns where it is.
    fn store_download(&self, temp_path: String, name: String, mime: String) -> Result<String, TandemError>;
}

struct VaultAdapter(Arc<dyn TandemVault>);

impl SecretStore for VaultAdapter {
    fn load(&self) -> crate::Result<Option<Vec<u8>>> {
        self.0.load().map_err(|e| crate::Error::Crypto(format!("the key store could not be read: {e}")))
    }

    fn save(&self, secret: &[u8]) -> crate::Result<()> {
        self.0
            .save(secret.to_vec())
            .map_err(|e| crate::Error::Crypto(format!("the key store could not be written: {e}")))
    }
}

struct FilesAdapter(Arc<dyn TandemFiles>);

impl FileStore for FilesAdapter {
    fn open_read(&self, source: &str) -> std::io::Result<std::fs::File> {
        // Where a descriptor cannot be handed over (Windows) the source is a path, and the core opens it itself.
        #[cfg(not(unix))]
        return std::fs::File::open(source);
        #[cfg(unix)]
        {
            let fd = self
                .0
                .open_read(source.to_string())
                .map_err(|e| std::io::Error::other(e.to_string()))?;
            file_from_descriptor(fd)
        }
    }

    fn store_download(&self, temp: &std::path::Path, name: &str, mime: &str) -> std::io::Result<String> {
        self.0
            .store_download(temp.to_string_lossy().into_owned(), name.to_string(), mime.to_string())
            .map_err(|e| std::io::Error::other(e.to_string()))
    }
}

/// The app detached the descriptor, so the file is ours to close.
#[cfg(unix)]
fn file_from_descriptor(fd: i32) -> std::io::Result<std::fs::File> {
    use std::os::fd::FromRawFd;
    Ok(unsafe { std::fs::File::from_raw_fd(fd) })
}

// ---- Plain types ------------------------------------------------------------------

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemPlatform {
    Android,
    MacOs,
    Linux,
    Windows,
    Ios,
    Other,
}

impl From<Platform> for TandemPlatform {
    fn from(p: Platform) -> Self {
        match p {
            Platform::Android => TandemPlatform::Android,
            Platform::MacOs => TandemPlatform::MacOs,
            Platform::Linux => TandemPlatform::Linux,
            Platform::Windows => TandemPlatform::Windows,
            Platform::Ios => TandemPlatform::Ios,
            Platform::Other => TandemPlatform::Other,
        }
    }
}

impl From<TandemPlatform> for Platform {
    fn from(p: TandemPlatform) -> Self {
        match p {
            TandemPlatform::Android => Platform::Android,
            TandemPlatform::MacOs => Platform::MacOs,
            TandemPlatform::Linux => Platform::Linux,
            TandemPlatform::Windows => Platform::Windows,
            TandemPlatform::Ios => Platform::Ios,
            TandemPlatform::Other => Platform::Other,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemRoute {
    Lan,
    Tailnet,
    Other,
}

impl From<Route> for TandemRoute {
    fn from(r: Route) -> Self {
        match r {
            Route::Lan => TandemRoute::Lan,
            Route::Tailnet => TandemRoute::Tailnet,
            Route::Other => TandemRoute::Other,
        }
    }
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemConfig {
    pub data_dir: String,
    pub device_name: String,
    pub platform: TandemPlatform,
    pub model: Option<String>,
    pub app_version: String,
    /// Zero picks a port. The default (47820) is tried first when this is 47820.
    pub port: u16,
    pub enable_mdns: bool,
    pub caps: Vec<String>,
    /// Longer keep-alives for a phone that is idle, to spare the battery.
    pub low_power: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemNetKind {
    None,
    Wifi,
    Cellular,
    Ethernet,
    Other,
}

impl From<NetKind> for TandemNetKind {
    fn from(k: NetKind) -> Self {
        match k {
            NetKind::None => TandemNetKind::None,
            NetKind::Wifi => TandemNetKind::Wifi,
            NetKind::Cellular => TandemNetKind::Cellular,
            NetKind::Ethernet => TandemNetKind::Ethernet,
            NetKind::Other => TandemNetKind::Other,
        }
    }
}

impl From<TandemNetKind> for NetKind {
    fn from(k: TandemNetKind) -> Self {
        match k {
            TandemNetKind::None => NetKind::None,
            TandemNetKind::Wifi => NetKind::Wifi,
            TandemNetKind::Cellular => NetKind::Cellular,
            TandemNetKind::Ethernet => NetKind::Ethernet,
            TandemNetKind::Other => NetKind::Other,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Record)]
pub struct TandemBattery {
    pub level: u8,
    pub charging: bool,
    pub power_save: bool,
}

#[derive(Clone, Debug, PartialEq, Eq, uniffi::Record)]
pub struct TandemNetwork {
    pub kind: TandemNetKind,
    pub ssid: Option<String>,
    pub metered: bool,
    pub roaming: bool,
    pub signal: Option<u8>,
}

/// A device's vitals. Send only what changed.
#[derive(Clone, Debug, Default, PartialEq, Eq, uniffi::Record)]
pub struct TandemStatus {
    pub battery: Option<TandemBattery>,
    pub network: Option<TandemNetwork>,
    pub hotspot: Option<bool>,
    pub dnd: Option<bool>,
    pub locked: Option<bool>,
    pub free_storage: Option<u64>,
    pub asleep: Option<bool>,
    pub wake_mac: Option<String>,
    pub muted: Option<bool>,
}

impl From<Status> for TandemStatus {
    fn from(s: Status) -> Self {
        TandemStatus {
            battery: s.battery.map(|b| TandemBattery { level: b.level, charging: b.charging, power_save: b.power_save }),
            network: s.network.map(|n| TandemNetwork {
                kind: n.kind.into(),
                ssid: n.ssid,
                metered: n.metered,
                roaming: n.roaming,
                signal: n.signal,
            }),
            hotspot: s.hotspot,
            dnd: s.dnd,
            locked: s.locked,
            free_storage: s.free_storage,
            asleep: s.asleep,
            wake_mac: s.wake_mac,
            muted: s.muted,
        }
    }
}

impl From<TandemStatus> for Status {
    fn from(s: TandemStatus) -> Self {
        Status {
            battery: s.battery.map(|b| Battery { level: b.level, charging: b.charging, power_save: b.power_save }),
            network: s.network.map(|n| NetworkStatus {
                kind: n.kind.into(),
                ssid: n.ssid,
                metered: n.metered,
                roaming: n.roaming,
                signal: n.signal,
            }),
            hotspot: s.hotspot,
            dnd: s.dnd,
            locked: s.locked,
            free_storage: s.free_storage,
            asleep: s.asleep,
            wake_mac: s.wake_mac,
            muted: s.muted,
        }
    }
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemDevice {
    pub id: String,
    pub name: String,
    pub platform: TandemPlatform,
    pub online: bool,
    pub route: Option<TandemRoute>,
    pub rtt_ms: Option<u32>,
    pub status: TandemStatus,
    pub app_version: Option<String>,
    pub caps: Vec<String>,
    pub vouched_by_removed: bool,
    pub clipboard_enabled: bool,
    pub auto_accept: bool,
    pub notifications_enabled: bool,
    /// Reachable over Bluetooth right now, though not over the network.
    pub ble: bool,
}

impl From<DeviceInfo> for TandemDevice {
    fn from(d: DeviceInfo) -> Self {
        TandemDevice {
            id: d.id.to_string(),
            name: d.name,
            platform: d.platform.into(),
            online: d.online,
            route: d.route.map(Into::into),
            rtt_ms: d.rtt_ms,
            status: d.status.into(),
            app_version: d.app_version,
            caps: d.caps,
            vouched_by_removed: d.vouched_by_removed,
            clipboard_enabled: d.settings.clipboard,
            auto_accept: d.settings.auto_accept,
            notifications_enabled: d.settings.notifications,
            ble: d.ble,
        }
    }
}

/// Something that can play on a device. See `proto::MediaPlayer`.
#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemMediaPlayer {
    pub id: String,
    pub app: String,
    pub title: String,
    pub artist: String,
    pub album: String,
    pub playing: bool,
    pub position_ms: Option<u64>,
    pub duration_ms: Option<u64>,
    pub can_prev: bool,
    pub can_next: bool,
    pub can_seek: bool,
    pub art: u64,
}

impl From<crate::proto::MediaPlayer> for TandemMediaPlayer {
    fn from(p: crate::proto::MediaPlayer) -> Self {
        TandemMediaPlayer {
            id: p.id,
            app: p.app,
            title: p.title,
            artist: p.artist,
            album: p.album,
            playing: p.playing,
            position_ms: p.position_ms,
            duration_ms: p.duration_ms,
            can_prev: p.can_prev,
            can_next: p.can_next,
            can_seek: p.can_seek,
            art: p.art,
        }
    }
}

impl From<TandemMediaPlayer> for crate::proto::MediaPlayer {
    fn from(p: TandemMediaPlayer) -> Self {
        crate::proto::MediaPlayer {
            id: p.id,
            app: p.app,
            title: p.title,
            artist: p.artist,
            album: p.album,
            playing: p.playing,
            position_ms: p.position_ms,
            duration_ms: p.duration_ms,
            can_prev: p.can_prev,
            can_next: p.can_next,
            can_seek: p.can_seek,
            art: p.art,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemMediaAction {
    Play,
    Pause,
    Toggle,
    Next,
    Previous,
    Seek,
}

impl From<TandemMediaAction> for crate::proto::MediaAction {
    fn from(a: TandemMediaAction) -> Self {
        use crate::proto::MediaAction as M;
        match a {
            TandemMediaAction::Play => M::Play,
            TandemMediaAction::Pause => M::Pause,
            TandemMediaAction::Toggle => M::Toggle,
            TandemMediaAction::Next => M::Next,
            TandemMediaAction::Previous => M::Previous,
            TandemMediaAction::Seek => M::Seek,
        }
    }
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemPairingOffer {
    pub uri: String,
    pub expires_at_ms: u64,
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemOutgoingFile {
    pub source: String,
    pub name: String,
    /// Zero means "look it up".
    pub size: u64,
    pub mime: String,
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemSendReport {
    pub offer: u64,
    pub sent_to: Vec<String>,
    pub offline: Vec<String>,
}

#[derive(Clone, Copy, Debug, uniffi::Enum)]
pub enum TandemShareOrigin {
    Files,
    Screenshot,
    Photo,
    Clipboard,
    /// The answer to a capture request, with the id of that request.
    Capture { request: u64 },
    Other,
}

impl From<TandemShareOrigin> for ShareOrigin {
    fn from(o: TandemShareOrigin) -> Self {
        match o {
            TandemShareOrigin::Files => ShareOrigin::Files,
            TandemShareOrigin::Screenshot => ShareOrigin::Screenshot,
            TandemShareOrigin::Photo => ShareOrigin::Photo,
            TandemShareOrigin::Clipboard => ShareOrigin::Clipboard,
            TandemShareOrigin::Capture { request } => ShareOrigin::Capture(request),
            TandemShareOrigin::Other => ShareOrigin::Other,
        }
    }
}

impl From<ShareOrigin> for TandemShareOrigin {
    fn from(o: ShareOrigin) -> Self {
        match o {
            ShareOrigin::Files => TandemShareOrigin::Files,
            ShareOrigin::Screenshot => TandemShareOrigin::Screenshot,
            ShareOrigin::Photo => TandemShareOrigin::Photo,
            ShareOrigin::Clipboard => TandemShareOrigin::Clipboard,
            ShareOrigin::Capture(request) => TandemShareOrigin::Capture { request },
            ShareOrigin::Other => TandemShareOrigin::Other,
        }
    }
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemShareItem {
    pub name: String,
    pub size: u64,
    pub mime: String,
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemButton {
    pub id: String,
    pub title: String,
    pub is_reply: bool,
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemNotification {
    pub key: String,
    pub app_id: String,
    pub app_name: String,
    pub title: String,
    pub text: String,
    pub sub_text: Option<String>,
    pub ts: u64,
    pub ongoing: bool,
    pub silent: bool,
    pub buttons: Vec<TandemButton>,
    pub otp: Option<String>,
    pub progress_done: Option<u32>,
    pub progress_total: Option<u32>,
}

impl From<NotificationMsg> for TandemNotification {
    fn from(n: NotificationMsg) -> Self {
        TandemNotification {
            key: n.key,
            app_id: n.app_id,
            app_name: n.app_name,
            title: n.title,
            text: n.text,
            sub_text: n.sub_text,
            ts: n.ts,
            ongoing: n.ongoing,
            silent: n.silent,
            buttons: n
                .buttons
                .into_iter()
                .map(|b| TandemButton { id: b.id, title: b.title, is_reply: b.is_reply })
                .collect(),
            otp: n.otp,
            progress_done: n.progress.map(|p| p.0),
            progress_total: n.progress.map(|p| p.1),
        }
    }
}

impl From<TandemNotification> for NotificationMsg {
    fn from(n: TandemNotification) -> Self {
        NotificationMsg {
            key: n.key,
            app_id: n.app_id,
            app_name: n.app_name,
            title: n.title,
            text: n.text,
            sub_text: n.sub_text,
            ts: n.ts,
            ongoing: n.ongoing,
            silent: n.silent,
            buttons: n
                .buttons
                .into_iter()
                .map(|b| NotifButton { id: b.id, title: b.title, is_reply: b.is_reply })
                .collect(),
            otp: n.otp,
            progress: match (n.progress_done, n.progress_total) {
                (Some(done), Some(total)) => Some((done, total)),
                _ => None,
            },
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemCallState {
    Ringing,
    Dialing,
    Active,
    Ended,
    Missed,
}

impl From<CallState> for TandemCallState {
    fn from(s: CallState) -> Self {
        match s {
            CallState::Ringing => TandemCallState::Ringing,
            CallState::Dialing => TandemCallState::Dialing,
            CallState::Active => TandemCallState::Active,
            CallState::Ended => TandemCallState::Ended,
            CallState::Missed => TandemCallState::Missed,
        }
    }
}

impl From<TandemCallState> for CallState {
    fn from(s: TandemCallState) -> Self {
        match s {
            TandemCallState::Ringing => CallState::Ringing,
            TandemCallState::Dialing => CallState::Dialing,
            TandemCallState::Active => CallState::Active,
            TandemCallState::Ended => CallState::Ended,
            TandemCallState::Missed => CallState::Missed,
        }
    }
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemCall {
    pub id: String,
    pub state: TandemCallState,
    pub incoming: bool,
    pub number: Option<String>,
    pub name: Option<String>,
    pub ts: u64,
}

#[derive(Clone, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemCallAction {
    Answer,
    Reject,
    Silence,
    Hangup,
    RejectWithMessage { message: String },
}

impl From<CallActionKind> for TandemCallAction {
    fn from(a: CallActionKind) -> Self {
        match a {
            CallActionKind::Answer => TandemCallAction::Answer,
            CallActionKind::Reject => TandemCallAction::Reject,
            CallActionKind::Silence => TandemCallAction::Silence,
            CallActionKind::Hangup => TandemCallAction::Hangup,
            CallActionKind::RejectWithMessage(message) => TandemCallAction::RejectWithMessage { message },
        }
    }
}

impl From<TandemCallAction> for CallActionKind {
    fn from(a: TandemCallAction) -> Self {
        match a {
            TandemCallAction::Answer => CallActionKind::Answer,
            TandemCallAction::Reject => CallActionKind::Reject,
            TandemCallAction::Silence => CallActionKind::Silence,
            TandemCallAction::Hangup => CallActionKind::Hangup,
            TandemCallAction::RejectWithMessage { message } => CallActionKind::RejectWithMessage(message),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemMediaKey {
    PlayPause,
    Next,
    Previous,
    VolumeUp,
    VolumeDown,
    Mute,
}

impl From<MediaKey> for TandemMediaKey {
    fn from(k: MediaKey) -> Self {
        match k {
            MediaKey::PlayPause => TandemMediaKey::PlayPause,
            MediaKey::Next => TandemMediaKey::Next,
            MediaKey::Previous => TandemMediaKey::Previous,
            MediaKey::VolumeUp => TandemMediaKey::VolumeUp,
            MediaKey::VolumeDown => TandemMediaKey::VolumeDown,
            MediaKey::Mute => TandemMediaKey::Mute,
        }
    }
}

impl From<TandemMediaKey> for MediaKey {
    fn from(k: TandemMediaKey) -> Self {
        match k {
            TandemMediaKey::PlayPause => MediaKey::PlayPause,
            TandemMediaKey::Next => MediaKey::Next,
            TandemMediaKey::Previous => MediaKey::Previous,
            TandemMediaKey::VolumeUp => MediaKey::VolumeUp,
            TandemMediaKey::VolumeDown => MediaKey::VolumeDown,
            TandemMediaKey::Mute => MediaKey::Mute,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemInput {
    Pointer { dx: i16, dy: i16 },
    Scroll { dx: i16, dy: i16 },
    Button { button: u8, down: bool },
    Click { button: u8, count: u8 },
    Key { code: u16, down: bool, mods: u8 },
    Text { text: String },
    Media { key: TandemMediaKey },
}

impl From<InputMsg> for TandemInput {
    fn from(i: InputMsg) -> Self {
        match i {
            InputMsg::Pointer { dx, dy } => TandemInput::Pointer { dx, dy },
            InputMsg::Scroll { dx, dy } => TandemInput::Scroll { dx, dy },
            InputMsg::Button { button, down } => TandemInput::Button { button, down },
            InputMsg::Click { button, count } => TandemInput::Click { button, count },
            InputMsg::Key { code, down, mods } => TandemInput::Key { code, down, mods },
            InputMsg::Text(text) => TandemInput::Text { text },
            InputMsg::Media(key) => TandemInput::Media { key: key.into() },
        }
    }
}

impl From<TandemInput> for InputMsg {
    fn from(i: TandemInput) -> Self {
        match i {
            TandemInput::Pointer { dx, dy } => InputMsg::Pointer { dx, dy },
            TandemInput::Scroll { dx, dy } => InputMsg::Scroll { dx, dy },
            TandemInput::Button { button, down } => InputMsg::Button { button, down },
            TandemInput::Click { button, count } => InputMsg::Click { button, count },
            TandemInput::Key { code, down, mods } => InputMsg::Key { code, down, mods },
            TandemInput::Text { text } => InputMsg::Text(text),
            TandemInput::Media { key } => InputMsg::Media(key.into()),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemHotspot {
    Request { reason: String },
    State { on: bool, ssid: Option<String>, clients: u8, data_used: Option<u64>, error: Option<String> },
    Stop,
}

impl From<HotspotMsg> for TandemHotspot {
    fn from(h: HotspotMsg) -> Self {
        match h {
            HotspotMsg::Request { reason } => TandemHotspot::Request { reason },
            HotspotMsg::State { on, ssid, clients, data_used, error } => {
                TandemHotspot::State { on, ssid, clients, data_used, error }
            }
            HotspotMsg::Stop => TandemHotspot::Stop,
        }
    }
}

impl From<TandemHotspot> for HotspotMsg {
    fn from(h: TandemHotspot) -> Self {
        match h {
            TandemHotspot::Request { reason } => HotspotMsg::Request { reason },
            TandemHotspot::State { on, ssid, clients, data_used, error } => {
                HotspotMsg::State { on, ssid, clients, data_used, error }
            }
            TandemHotspot::Stop => HotspotMsg::Stop,
        }
    }
}

/// What the phone is asked to make. A kind this version does not know never reaches the app.
#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemCaptureKind {
    Photo,
    Document,
    Picture,
}

impl From<TandemCaptureKind> for CaptureKind {
    fn from(k: TandemCaptureKind) -> Self {
        match k {
            TandemCaptureKind::Photo => CaptureKind::Photo,
            TandemCaptureKind::Document => CaptureKind::Document,
            TandemCaptureKind::Picture => CaptureKind::Picture,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemCaptureWhy {
    Cancelled,
    /// The phone is not allowed to use the camera.
    Refused,
    Unavailable,
    Other,
}

impl From<TandemCaptureWhy> for CaptureWhy {
    fn from(w: TandemCaptureWhy) -> Self {
        match w {
            TandemCaptureWhy::Cancelled => CaptureWhy::Cancelled,
            TandemCaptureWhy::Refused => CaptureWhy::Refused,
            TandemCaptureWhy::Unavailable => CaptureWhy::Unavailable,
            TandemCaptureWhy::Other => CaptureWhy::Other,
        }
    }
}

impl From<CaptureWhy> for TandemCaptureWhy {
    fn from(w: CaptureWhy) -> Self {
        match w {
            CaptureWhy::Cancelled => TandemCaptureWhy::Cancelled,
            CaptureWhy::Refused => TandemCaptureWhy::Refused,
            CaptureWhy::Unavailable => TandemCaptureWhy::Unavailable,
            CaptureWhy::Other => TandemCaptureWhy::Other,
        }
    }
}

#[derive(Clone, Debug, uniffi::Enum)]
pub enum TandemEvent {
    DevicesChanged,
    Connected { id: String },
    Disconnected { id: String },
    Paired { id: String },
    CircleChanged,
    RemovedFromCircle,
    Clipboard { from: String, text: String, is_url: bool },
    ShareOffered { from: String, offer: u64, origin: TandemShareOrigin, items: Vec<TandemShareItem> },
    ShareText { from: String, text: String, is_url: bool, open: bool },
    Progress { offer: u64, index: u32, peer: String, incoming: bool, name: String, done: u64, total: u64 },
    Finished {
        offer: u64,
        index: u32,
        peer: String,
        incoming: bool,
        name: String,
        size: u64,
        location: Option<String>,
        error: Option<String>,
    },
    Notification { from: String, notification: TandemNotification },
    NotificationRemoved { from: String, key: String },
    NotificationAction { from: String, key: String, button: String, reply: Option<String>, dismiss: bool },
    AppIcon { from: String, app_id: String, png: Vec<u8> },
    Call { from: String, call: TandemCall },
    CallAction { from: String, id: String, action: TandemCallAction },
    Dial { from: String, number: String },
    Ring { from: String, on: bool },
    Input { from: String, input: TandemInput },
    Hotspot { from: String, hotspot: TandemHotspot },
    /// The other device wants a picture. Answer with `send_files` and origin `Capture { request: id }`,
    /// or with `cancel_capture`.
    CaptureRequested { from: String, id: u64, kind: TandemCaptureKind },
    CaptureCancelled { from: String, id: u64, why: TandemCaptureWhy },
    MediaPlayers { from: String, players: Vec<TandemMediaPlayer> },
    MediaArt { from: String, key: u64, jpeg: Vec<u8> },
    /// `action` is None for a command this version does not know.
    MediaCommand { from: String, player: String, action: Option<TandemMediaAction>, position_ms: Option<u64> },
    /// The other device is about to send its sound: 16 bit signed samples, interleaved.
    AudioStart { from: String, stream: u8, sample_rate: u32, channels: u8 },
    AudioStop { from: String, stream: u8 },
    /// Another device asks for the screen or the camera of this one. The same news as `TandemMediaHost.on_request`.
    MediaRequested { from: String, request: TandemMediaRequest, pre_approved: bool },
    MediaStarted { peer: String, session: u64, kind: TandemMediaKind, role: TandemMediaRole },
    MediaEnded { peer: String, session: u64, kind: TandemMediaKind, role: TandemMediaRole, reason: TandemMediaEnd },
    /// The bitrate the encoder of a host session should move to.
    MediaBitrate { peer: String, session: u64, bits_per_second: u32 },
}

impl From<Event> for TandemEvent {
    fn from(event: Event) -> Self {
        match event {
            Event::DevicesChanged => TandemEvent::DevicesChanged,
            Event::Connected { id } => TandemEvent::Connected { id: id.to_string() },
            Event::Disconnected { id } => TandemEvent::Disconnected { id: id.to_string() },
            Event::Paired { id } => TandemEvent::Paired { id: id.to_string() },
            Event::CircleChanged => TandemEvent::CircleChanged,
            Event::RemovedFromCircle => TandemEvent::RemovedFromCircle,
            Event::Clipboard { from, text, is_url } => TandemEvent::Clipboard { from: from.to_string(), text, is_url },
            Event::ShareOffered { from, offer } => TandemEvent::ShareOffered {
                from: from.to_string(),
                offer: offer.id,
                origin: offer.origin.into(),
                items: offer
                    .items
                    .into_iter()
                    .map(|i| TandemShareItem { name: i.name, size: i.size, mime: i.mime })
                    .collect(),
            },
            Event::ShareText { from, text, is_url, open } => {
                TandemEvent::ShareText { from: from.to_string(), text, is_url, open }
            }
            Event::Progress(p) => TandemEvent::Progress {
                offer: p.offer,
                index: p.index,
                peer: p.peer.to_string(),
                incoming: p.incoming,
                name: p.name,
                done: p.done,
                total: p.total,
            },
            Event::Finished(d) => TandemEvent::Finished {
                offer: d.offer,
                index: d.index,
                peer: d.peer.to_string(),
                incoming: d.incoming,
                name: d.name,
                size: d.size,
                location: d.location,
                error: d.error,
            },
            Event::Notification { from, notification } => {
                TandemEvent::Notification { from: from.to_string(), notification: notification.into() }
            }
            Event::NotificationRemoved { from, key } => TandemEvent::NotificationRemoved { from: from.to_string(), key },
            Event::NotificationAction { from, action } => TandemEvent::NotificationAction {
                from: from.to_string(),
                key: action.key,
                button: action.button,
                reply: action.reply,
                dismiss: action.dismiss,
            },
            Event::AppIcon { from, app_id, png } => TandemEvent::AppIcon { from: from.to_string(), app_id, png },
            Event::Call { from, call } => TandemEvent::Call {
                from: from.to_string(),
                call: TandemCall {
                    id: call.id,
                    state: call.state.into(),
                    incoming: call.incoming,
                    number: call.number,
                    name: call.name,
                    ts: call.ts,
                },
            },
            Event::CallAction { from, action } => {
                TandemEvent::CallAction { from: from.to_string(), id: action.id, action: action.action.into() }
            }
            Event::Dial { from, number } => TandemEvent::Dial { from: from.to_string(), number },
            Event::Ring { from, on } => TandemEvent::Ring { from: from.to_string(), on },
            Event::Input { from, input } => TandemEvent::Input { from: from.to_string(), input: input.into() },
            Event::Hotspot { from, hotspot } => TandemEvent::Hotspot { from: from.to_string(), hotspot: hotspot.into() },
            Event::CaptureRequested { from, id, kind } => {
                let kind = match kind {
                    CaptureKind::Document => TandemCaptureKind::Document,
                    CaptureKind::Picture => TandemCaptureKind::Picture,
                    _ => TandemCaptureKind::Photo,
                };
                TandemEvent::CaptureRequested { from: from.to_string(), id, kind }
            }
            Event::CaptureCancelled { from, id, why } => {
                TandemEvent::CaptureCancelled { from: from.to_string(), id, why: why.into() }
            }
            Event::MediaPlayers { from, players } => {
                TandemEvent::MediaPlayers { from: from.to_string(), players: players.into_iter().map(Into::into).collect() }
            }
            Event::MediaArt { from, key, jpeg } => TandemEvent::MediaArt { from: from.to_string(), key, jpeg },
            Event::AudioStart { from, stream, sample_rate, channels } => {
                TandemEvent::AudioStart { from: from.to_string(), stream, sample_rate, channels }
            }
            Event::AudioStop { from, stream } => TandemEvent::AudioStop { from: from.to_string(), stream },
            Event::MediaRequested { from, request, pre_approved } => {
                TandemEvent::MediaRequested { from: from.to_string(), request: request.into(), pre_approved }
            }
            Event::MediaStarted { peer, session, kind, role } => {
                TandemEvent::MediaStarted { peer: peer.to_string(), session, kind: kind.into(), role: role.into() }
            }
            Event::MediaEnded { peer, session, kind, role, reason } => TandemEvent::MediaEnded {
                peer: peer.to_string(),
                session,
                kind: kind.into(),
                role: role.into(),
                reason: reason.into(),
            },
            Event::MediaBitrate { peer, session, bits_per_second } => {
                TandemEvent::MediaBitrate { peer: peer.to_string(), session, bits_per_second }
            }
            Event::MediaCommand { from, player, action, position_ms } => {
                use crate::proto::MediaAction as M;
                let action = match action {
                    M::Play => Some(TandemMediaAction::Play),
                    M::Pause => Some(TandemMediaAction::Pause),
                    M::Toggle => Some(TandemMediaAction::Toggle),
                    M::Next => Some(TandemMediaAction::Next),
                    M::Previous => Some(TandemMediaAction::Previous),
                    M::Seek => Some(TandemMediaAction::Seek),
                    M::Other => None,
                };
                TandemEvent::MediaCommand { from: from.to_string(), player, action, position_ms }
            }
        }
    }
}

/// The players of the other device worth showing next to this device's own: the ones that play
/// something a local player already plays are left out, so a phone that only remote controls the
/// Mac's Spotify does not give a second Spotify. Both apps call this, so they cannot disagree.
#[uniffi::export]
pub fn tandem_media_visible(local: Vec<TandemMediaPlayer>, remote: Vec<TandemMediaPlayer>) -> Vec<TandemMediaPlayer> {
    let local: Vec<crate::proto::MediaPlayer> = local.into_iter().map(Into::into).collect();
    let remote: Vec<crate::proto::MediaPlayer> = remote.into_iter().map(Into::into).collect();
    crate::media::visible(&local, &remote).into_iter().map(Into::into).collect()
}

/// The one-time verification code in the text of a message or notification, or nothing. Every app calls this one
/// function, so a code is recognised the same way on the phone, the Mac and Windows.
#[uniffi::export]
pub fn tandem_find_code(text: String) -> Option<String> {
    crate::otp::find_code(&text)
}

// ---- Hotspot over Bluetooth ------------------------------------------------------

/// The bytes a hotspot request signs. Both apps call this, so they cannot disagree.
#[uniffi::export]
pub fn tandem_hotspot_auth_message(challenge: Vec<u8>, device_id: String, action: u8, timestamp_ms: u64) -> Vec<u8> {
    crate::hotspot::auth_message(&challenge, &device_id, action, timestamp_ms)
}

/// The rotating tag in a phone's Bluetooth advertisement for `hour` (Unix time in
/// seconds divided by 3600). Empty when the id is not a valid device id.
#[uniffi::export]
pub fn tandem_ble_hint(device_id: String, hour: u64) -> Vec<u8> {
    match DeviceId::parse(&device_id) {
        Ok(id) => crate::hotspot::ble_hint(&id, hour).to_vec(),
        Err(_) => Vec::new(),
    }
}

// ---- Logging ----------------------------------------------------------------------

static LOGGING: Once = Once::new();

/// Routes the core's logs to the platform log (logcat on Android, the unified log on
/// Apple systems). Safe to call more than once.
#[uniffi::export]
pub fn tandem_init_logging(verbose: bool) {
    LOGGING.call_once(|| {
        let level = if verbose { log::LevelFilter::Debug } else { log::LevelFilter::Info };
        #[cfg(target_os = "android")]
        android_logger::init_once(android_logger::Config::default().with_max_level(level).with_tag("Tandem"));
        #[cfg(target_vendor = "apple")]
        {
            let _ = oslog::OsLogger::new("nl.markmaaktmedia.Tandem").level_filter(level).init();
        }
        #[cfg(not(any(target_os = "android", target_vendor = "apple")))]
        let _ = level;
    });
}

// ---- The engine -------------------------------------------------------------------

/// Owns the runtime and shuts it down without blocking, so dropping the engine from
/// any thread (including one that belongs to another runtime) is safe.
struct OwnedRuntime(Option<Runtime>);

impl std::ops::Deref for OwnedRuntime {
    type Target = Runtime;

    fn deref(&self) -> &Runtime {
        self.0.as_ref().expect("runtime is alive until drop")
    }
}

impl Drop for OwnedRuntime {
    fn drop(&mut self) {
        if let Some(runtime) = self.0.take() {
            runtime.shutdown_background();
        }
    }
}

#[derive(uniffi::Object)]
pub struct TandemEngine {
    runtime: OwnedRuntime,
    engine: Engine,
    /// The files of other devices that are served as drives on this machine, by device.
    #[cfg(feature = "webdav")]
    drives: std::sync::Mutex<std::collections::HashMap<String, crate::webdav::WebDavShare>>,
}

fn parse_ids(ids: &[String]) -> Result<Vec<DeviceId>, TandemError> {
    ids.iter()
        .map(|id| DeviceId::parse(id).map_err(TandemError::from))
        .collect()
}

fn ids_to_strings(ids: Vec<DeviceId>) -> Vec<String> {
    ids.into_iter().map(|id| id.to_string()).collect()
}

#[uniffi::export(async_runtime = "tokio")]
impl TandemEngine {
    /// Starts the engine. Call it from a background thread: it opens the socket and
    /// announces on the network.
    #[uniffi::constructor]
    pub fn start(
        config: TandemConfig,
        vault: Arc<dyn TandemVault>,
        files: Arc<dyn TandemFiles>,
        sink: Arc<dyn TandemEventSink>,
    ) -> Result<Arc<TandemEngine>, TandemError> {
        let runtime = tokio::runtime::Builder::new_multi_thread()
            .worker_threads(2)
            .thread_name("tandem")
            .enable_all()
            .build()
            .map_err(|e| TandemError::Failed { reason: e.to_string() })?;

        let mut cfg = EngineConfig::new(&config.data_dir, &config.device_name);
        cfg.platform = config.platform.into();
        cfg.model = config.model;
        cfg.app_version = config.app_version;
        cfg.port = config.port;
        cfg.enable_mdns = config.enable_mdns;
        cfg.caps = config.caps;
        if config.low_power {
            cfg.tuning.keep_alive = std::time::Duration::from_secs(25);
            cfg.tuning.idle_timeout = std::time::Duration::from_secs(70);
        }

        let engine = runtime
            .block_on(Engine::start(cfg, Arc::new(VaultAdapter(vault)), Arc::new(FilesAdapter(files))))
            .map_err(TandemError::from)?;

        let mut events = engine.subscribe();
        runtime.spawn(async move {
            loop {
                match events.recv().await {
                    Ok(event) => sink.on_event(event.into()),
                    Err(RecvError::Lagged(missed)) => {
                        tracing::warn!("the app fell behind by {missed} events");
                        sink.on_event(TandemEvent::DevicesChanged);
                    }
                    Err(RecvError::Closed) => break,
                }
            }
        });

        Ok(Arc::new(TandemEngine {
            runtime: OwnedRuntime(Some(runtime)),
            engine,
            #[cfg(feature = "webdav")]
            drives: Default::default(),
        }))
    }

    pub fn id(&self) -> String {
        self.engine.id().to_string()
    }

    pub fn name(&self) -> String {
        self.engine.name()
    }

    pub fn port(&self) -> u16 {
        self.engine.port()
    }

    pub fn devices(&self) -> Vec<TandemDevice> {
        self.engine.devices().into_iter().map(Into::into).collect()
    }

    pub fn is_member(&self) -> bool {
        self.engine.is_member()
    }

    /// Call when Wi-Fi, mobile data or the VPN changed.
    pub fn network_changed(&self) {
        let _guard = self.runtime.enter();
        self.engine.network_changed();
    }

    /// Signs with this device's identity key. Used for proofs that cannot travel over
    /// QUIC, such as the Bluetooth hotspot request.
    pub fn sign_message(&self, message: Vec<u8>) -> Vec<u8> {
        self.engine.sign_message(&message)
    }

    /// True only when `id` is a current circle member and the signature is theirs.
    pub fn verify_member(&self, id: String, message: Vec<u8>, signature: Vec<u8>) -> bool {
        DeviceId::parse(&id).map(|id| self.engine.verify_member(&id, &message, &signature)).unwrap_or(false)
    }

    // ---- Bluetooth messages ------------------------------------------------------
    //
    // The app only moves writes: what to send comes out of `ble_take_outbox` and what
    // arrives goes into `ble_receive`. Sealing, cutting into pieces and putting them back
    // together all happen here.

    /// True once this device and `id` share the key that seals Bluetooth frames. It is
    /// made when they first connect over the network.
    pub fn ble_ready(&self, id: String) -> bool {
        DeviceId::parse(&id).map(|id| self.engine.ble_ready(&id)).unwrap_or(false)
    }

    /// The first writes to send on a new link, so the other end learns who this is.
    pub fn ble_hello(&self, id: String, chunk_size: u32) -> Vec<Vec<u8>> {
        DeviceId::parse(&id).map(|id| self.engine.ble_hello(&id, chunk_size as usize)).unwrap_or_default()
    }

    /// The writes waiting for `id`, each at most `chunk_size` bytes, oldest first. Empty
    /// when nothing waits. Call it on a timer while a link is up.
    pub fn ble_take_outbox(&self, id: String, chunk_size: u32) -> Vec<Vec<u8>> {
        DeviceId::parse(&id).map(|id| self.engine.ble_take_outbox(&id, chunk_size as usize)).unwrap_or_default()
    }

    /// One write that arrived on the link `link` (any stable name for it, such as the
    /// Bluetooth address). Returns the device id once a whole message from a circle member
    /// has arrived and been handled, which also marks that device as reachable over this link.
    pub async fn ble_receive(&self, link: String, chunk: Vec<u8>) -> Option<String> {
        let engine = self.engine.clone();
        let from = self.runtime.spawn(async move { engine.ble_receive(&link, &chunk).await }).await.ok()??;
        Some(from.to_string())
    }

    /// The link to `id` closed.
    pub fn ble_link_down(&self, id: String) {
        if let Ok(id) = DeviceId::parse(&id) {
            self.engine.ble_link_down(&id);
        }
    }

    /// The link named `link` closed: forget what it had half delivered.
    pub fn ble_drop_link(&self, link: String) {
        self.engine.ble_drop_link(&link);
    }

    /// Where a circle member can be reached right now, as `ip:port`. Dials at once.
    pub fn add_address(&self, id: String, addr: String) -> Result<(), TandemError> {
        let _guard = self.runtime.enter();
        let id = DeviceId::parse(&id)?;
        self.engine.add_address(&id, &addr).map_err(Into::into)
    }

    pub fn create_pairing_offer(&self) -> Result<TandemPairingOffer, TandemError> {
        let offer = self.engine.create_pairing_offer()?;
        Ok(TandemPairingOffer { uri: offer.uri, expires_at_ms: offer.expires_at })
    }

    pub fn cancel_pairing_offer(&self) {
        self.engine.cancel_pairing_offer();
    }

    pub fn set_device_settings(
        &self,
        id: String,
        clipboard: bool,
        auto_accept: bool,
        notifications: bool,
    ) -> Result<(), TandemError> {
        let id = DeviceId::parse(&id)?;
        self.engine
            .set_device_settings(&id, DeviceSettings { clipboard, auto_accept, notifications })
            .map_err(Into::into)
    }

    pub fn accept_offer(&self, from: String, offer: u64) -> Result<(), TandemError> {
        let _guard = self.runtime.enter();
        self.engine.accept_offer(DeviceId::parse(&from)?, offer).map_err(Into::into)
    }

    pub fn is_connected(&self, id: String) -> bool {
        DeviceId::parse(&id).map(|id| self.engine.is_connected(&id)).unwrap_or(false)
    }

    /// Sends a pointer movement without waiting for delivery.
    pub fn send_pointer(&self, id: String, dx: i16, dy: i16) -> Result<(), TandemError> {
        let id = DeviceId::parse(&id)?;
        self.engine.send_datagram(&id, crate::session::pointer_datagram(dx, dy)).map_err(Into::into)
    }

    pub fn send_scroll(&self, id: String, dx: i16, dy: i16) -> Result<(), TandemError> {
        let id = DeviceId::parse(&id)?;
        self.engine.send_datagram(&id, crate::session::scroll_datagram(dx, dy)).map_err(Into::into)
    }

    pub async fn pair_with_uri(&self, uri: String) -> Result<String, TandemError> {
        let engine = self.engine.clone();
        let id = self
            .runtime
            .spawn(async move { engine.pair_with_uri(&uri).await })
            .await
            .map_err(join_error)??;
        Ok(id.to_string())
    }

    pub async fn remove_device(&self, id: String) -> Result<(), TandemError> {
        let id = DeviceId::parse(&id)?;
        let engine = self.engine.clone();
        self.runtime.spawn(async move { engine.remove_device(id).await }).await.map_err(join_error)??;
        Ok(())
    }

    pub async fn rename_self(&self, name: String) -> Result<(), TandemError> {
        let engine = self.engine.clone();
        self.runtime.spawn(async move { engine.rename_self(&name).await }).await.map_err(join_error)??;
        Ok(())
    }

    pub async fn send_files(
        &self,
        targets: Vec<String>,
        files: Vec<TandemOutgoingFile>,
        origin: TandemShareOrigin,
    ) -> Result<TandemSendReport, TandemError> {
        let targets = parse_ids(&targets)?;
        let files: Vec<OutgoingFile> = files
            .into_iter()
            .map(|f| OutgoingFile { source: f.source, name: f.name, size: f.size, mime: f.mime })
            .collect();
        let engine = self.engine.clone();
        let report = self
            .runtime
            .spawn(async move { engine.send_files(&targets, files, origin.into()).await })
            .await
            .map_err(join_error)??;
        Ok(TandemSendReport {
            offer: report.offer,
            sent_to: ids_to_strings(report.sent_to),
            offline: ids_to_strings(report.offline),
        })
    }

    pub async fn send_bytes(
        &self,
        targets: Vec<String>,
        name: String,
        mime: String,
        data: Vec<u8>,
        origin: TandemShareOrigin,
    ) -> Result<TandemSendReport, TandemError> {
        let targets = parse_ids(&targets)?;
        let engine = self.engine.clone();
        let report = self
            .runtime
            .spawn(async move { engine.send_bytes(&targets, &name, &mime, data, origin.into()).await })
            .await
            .map_err(join_error)??;
        Ok(TandemSendReport {
            offer: report.offer,
            sent_to: ids_to_strings(report.sent_to),
            offline: ids_to_strings(report.offline),
        })
    }

    pub async fn send_text(
        &self,
        targets: Vec<String>,
        text: String,
        is_url: bool,
        open: bool,
    ) -> Result<Vec<String>, TandemError> {
        let targets = parse_ids(&targets)?;
        let engine = self.engine.clone();
        let reached = self
            .runtime
            .spawn(async move { engine.send_text(&targets, &text, is_url, open).await })
            .await
            .map_err(join_error)?;
        Ok(ids_to_strings(reached))
    }

    pub async fn clipboard_changed(&self, text: String, is_url: bool) {
        let engine = self.engine.clone();
        let _ = self.runtime.spawn(async move { engine.clipboard_changed(&text, is_url).await }).await;
    }

    pub async fn send_clipboard(
        &self,
        targets: Vec<String>,
        text: String,
        is_url: bool,
    ) -> Result<Vec<String>, TandemError> {
        let targets = parse_ids(&targets)?;
        let engine = self.engine.clone();
        let reached = self
            .runtime
            .spawn(async move { engine.send_clipboard(&targets, &text, is_url).await })
            .await
            .map_err(join_error)?;
        Ok(ids_to_strings(reached))
    }

    pub async fn update_status(&self, status: TandemStatus) {
        let engine = self.engine.clone();
        let _ = self.runtime.spawn(async move { engine.update_status(status.into()).await }).await;
    }

    /// Where the sound of other devices goes. Set it before anyone sends any.
    pub fn set_audio_sink(&self, sink: Arc<dyn TandemAudioSink>) {
        self.engine.set_audio_sink(Arc::new(AudioAdapter(sink)));
    }

    /// How many bytes of samples fit in one packet to this device, 0 when it is not connected.
    pub fn audio_payload_limit(&self, id: String) -> u32 {
        DeviceId::parse(&id).map(|id| self.engine.audio_payload_limit(&id) as u32).unwrap_or(0)
    }

    /// Sends one packet of sound without waiting. Packets that get lost stay lost.
    pub fn send_audio(&self, target: String, stream: u8, seq: u32, pcm: Vec<u8>) -> Result<(), TandemError> {
        let id = DeviceId::parse(&target)?;
        self.engine.send_audio(&id, stream, seq, &pcm).map_err(Into::into)
    }

    pub async fn send_audio_start(&self, target: String, stream: u8, sample_rate: u32, channels: u8) -> Result<(), TandemError> {
        self.send(vec![target], crate::proto::Msg::AudioStart { stream, sample_rate, channels }).await.map(|_| ())
    }

    pub async fn send_audio_stop(&self, target: String, stream: u8) -> Result<(), TandemError> {
        self.send(vec![target], crate::proto::Msg::AudioStop { stream }).await.map(|_| ())
    }

    /// This device's players, whole list, to the devices that should show them.
    pub async fn send_media_players(
        &self,
        targets: Vec<String>,
        players: Vec<TandemMediaPlayer>,
    ) -> Result<Vec<String>, TandemError> {
        self.send(targets, crate::proto::Msg::MediaPlayers { players: players.into_iter().map(Into::into).collect() }).await
    }

    /// A cover for the players' `art` key. Sent once per cover.
    pub async fn send_media_art(&self, targets: Vec<String>, key: u64, jpeg: Vec<u8>) -> Result<Vec<String>, TandemError> {
        self.send(targets, crate::proto::Msg::MediaArt { key, jpeg: serde_bytes::ByteBuf::from(jpeg) }).await
    }

    /// Asks `target` to do something with one of its players.
    pub async fn send_media_command(
        &self,
        target: String,
        player: String,
        action: TandemMediaAction,
        position_ms: Option<u64>,
    ) -> Result<(), TandemError> {
        self.send(vec![target], crate::proto::Msg::MediaCommand { player, action: action.into(), position_ms })
            .await
            .map(|_| ())
    }

    pub async fn send_notification(
        &self,
        targets: Vec<String>,
        notification: TandemNotification,
    ) -> Result<Vec<String>, TandemError> {
        self.send(targets, crate::proto::Msg::Notification(notification.into())).await
    }

    pub async fn remove_notification(&self, targets: Vec<String>, key: String) -> Result<Vec<String>, TandemError> {
        self.send(targets, crate::proto::Msg::NotificationRemoved { key }).await
    }

    pub async fn notification_action(
        &self,
        target: String,
        key: String,
        button: String,
        reply: Option<String>,
        dismiss: bool,
    ) -> Result<(), TandemError> {
        let msg = crate::proto::Msg::NotificationAction(NotificationAction { key, button, reply, dismiss });
        self.send(vec![target], msg).await.map(|_| ())
    }

    pub async fn send_app_icon(&self, targets: Vec<String>, app_id: String, png: Vec<u8>) -> Result<Vec<String>, TandemError> {
        self.send(targets, crate::proto::Msg::AppIcon { app_id, png: crate::proto::bytes(png) }).await
    }

    pub async fn send_call(&self, targets: Vec<String>, call: TandemCall) -> Result<Vec<String>, TandemError> {
        let msg = crate::proto::Msg::Call(CallMsg {
            id: call.id,
            state: call.state.into(),
            incoming: call.incoming,
            number: call.number,
            name: call.name,
            ts: call.ts,
        });
        self.send(targets, msg).await
    }

    pub async fn call_action(&self, target: String, id: String, action: TandemCallAction) -> Result<(), TandemError> {
        let msg = crate::proto::Msg::CallAction(crate::proto::CallAction { id, action: action.into() });
        self.send(vec![target], msg).await.map(|_| ())
    }

    pub async fn dial(&self, target: String, number: String) -> Result<(), TandemError> {
        self.send(vec![target], crate::proto::Msg::Dial { number }).await.map(|_| ())
    }

    pub async fn ring(&self, target: String, on: bool) -> Result<(), TandemError> {
        self.send(vec![target], crate::proto::Msg::Ring { on }).await.map(|_| ())
    }

    pub async fn send_input(&self, target: String, input: TandemInput) -> Result<(), TandemError> {
        self.send(vec![target], crate::proto::Msg::Input(input.into())).await.map(|_| ())
    }

    pub async fn send_hotspot(&self, target: String, hotspot: TandemHotspot) -> Result<(), TandemError> {
        self.send(vec![target], crate::proto::Msg::Hotspot(hotspot.into())).await.map(|_| ())
    }

    /// Asks a device for a picture. Fails with `NotConnected` when it is not online, so the asker can say so
    /// at once instead of waiting.
    pub async fn request_capture(&self, target: String, id: u64, kind: TandemCaptureKind) -> Result<(), TandemError> {
        let msg = crate::proto::Msg::CaptureRequest(crate::proto::CaptureRequest { id, kind: kind.into() });
        self.send(vec![target], msg).await.map(|_| ())
    }

    pub async fn cancel_capture(&self, target: String, id: u64, why: TandemCaptureWhy) -> Result<(), TandemError> {
        let msg = crate::proto::Msg::CaptureCancel(crate::proto::CaptureCancel { id, why: why.into() });
        self.send(vec![target], msg).await.map(|_| ())
    }

    pub async fn decline_offer(&self, from: String, offer: u64) -> Result<(), TandemError> {
        let from = DeviceId::parse(&from)?;
        let engine = self.engine.clone();
        self.runtime.spawn(async move { engine.decline_offer(from, offer).await }).await.map_err(join_error)?;
        Ok(())
    }

    pub async fn shutdown(&self) {
        let engine = self.engine.clone();
        let _ = self.runtime.spawn(async move { engine.shutdown().await }).await;
    }
}

impl TandemEngine {
    async fn send(&self, targets: Vec<String>, msg: crate::proto::Msg) -> Result<Vec<String>, TandemError> {
        let targets = parse_ids(&targets)?;
        let wanted = targets.len();
        let engine = self.engine.clone();
        let reached = self
            .runtime
            .spawn(async move { engine.send_msg(&targets, msg).await })
            .await
            .map_err(join_error)?;
        if reached.is_empty() && wanted > 0 {
            return Err(TandemError::NotConnected);
        }
        Ok(ids_to_strings(reached))
    }
}

fn join_error(e: tokio::task::JoinError) -> TandemError {
    TandemError::Failed { reason: format!("internal error: {e}") }
}

// ---- Files ------------------------------------------------------------------------

/// A folder that is offered to other devices.
#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemShare {
    pub name: String,
    pub path: String,
    pub write: bool,
}

/// What a device may do with the files of this one. See `files::FilePolicy`.
#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemFilePolicy {
    pub enabled: bool,
    pub shares: Vec<TandemShare>,
    pub write: bool,
    pub delete: bool,
    pub hidden: bool,
    pub max_upload: u64,
}

impl From<crate::files::FilePolicy> for TandemFilePolicy {
    fn from(p: crate::files::FilePolicy) -> Self {
        TandemFilePolicy {
            enabled: p.enabled,
            shares: p.shares.into_iter().map(|s| TandemShare { name: s.name, path: s.path, write: s.write }).collect(),
            write: p.write,
            delete: p.delete,
            hidden: p.hidden,
            max_upload: p.max_upload,
        }
    }
}

impl From<TandemFilePolicy> for crate::files::FilePolicy {
    fn from(p: TandemFilePolicy) -> Self {
        crate::files::FilePolicy {
            enabled: p.enabled,
            shares: p.shares.into_iter().map(|s| crate::files::Share { name: s.name, path: s.path, write: s.write }).collect(),
            write: p.write,
            delete: p.delete,
            hidden: p.hidden,
            max_upload: p.max_upload,
        }
    }
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemFsRoot {
    pub name: String,
    pub write: bool,
}

#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemFsEntry {
    pub name: String,
    pub dir: bool,
    pub size: u64,
    pub modified_ms: u64,
    pub readonly: bool,
}

impl From<crate::files::FsEntry> for TandemFsEntry {
    fn from(e: crate::files::FsEntry) -> Self {
        TandemFsEntry { name: e.name, dir: e.dir, size: e.size, modified_ms: e.modified_ms, readonly: e.readonly }
    }
}

/// One thing another device did to the files of this one.
#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemFileActivity {
    pub at_ms: u64,
    pub device: String,
    pub action: String,
    pub path: String,
    pub ok: bool,
    pub detail: String,
}

/// Hears how far a file has come. Called on a runtime thread, so it must only note the numbers and return.
#[uniffi::export(foreign)]
pub trait TandemFsProgress: Send + Sync {
    fn progress(&self, done: u64, total: u64);
}

/// The folders that are offered when nobody has chosen any.
#[uniffi::export]
pub fn tandem_default_shares() -> Vec<TandemShare> {
    crate::files::default_shares().into_iter().map(|s| TandemShare { name: s.name, path: s.path, write: s.write }).collect()
}

#[uniffi::export(async_runtime = "tokio")]
impl TandemEngine {
    // What other devices may do with the files here.

    pub fn file_policy(&self, id: String) -> Result<TandemFilePolicy, TandemError> {
        Ok(self.engine.file_policy(&DeviceId::parse(&id)?).into())
    }

    /// Whether the device has choices of its own, or is on the default.
    pub fn has_own_file_policy(&self, id: String) -> bool {
        DeviceId::parse(&id).map(|id| self.engine.has_own_file_policy(&id)).unwrap_or(false)
    }

    pub fn file_default_policy(&self) -> TandemFilePolicy {
        self.engine.file_default_policy().into()
    }

    pub fn set_file_policy(&self, id: String, policy: TandemFilePolicy) -> Result<(), TandemError> {
        self.engine.set_file_policy(&DeviceId::parse(&id)?, policy.into()).map_err(Into::into)
    }

    /// Back to the default for this device.
    pub fn clear_file_policy(&self, id: String) -> Result<(), TandemError> {
        self.engine.clear_file_policy(&DeviceId::parse(&id)?).map_err(Into::into)
    }

    pub fn set_file_default_policy(&self, policy: TandemFilePolicy) -> Result<(), TandemError> {
        self.engine.set_file_default_policy(policy.into()).map_err(Into::into)
    }

    /// What other devices did to the files here, newest first.
    pub fn file_activity(&self) -> Vec<TandemFileActivity> {
        self.engine
            .file_activity()
            .into_iter()
            .map(|a| TandemFileActivity { at_ms: a.at_ms, device: a.peer.to_string(), action: a.action, path: a.path, ok: a.ok, detail: a.detail })
            .collect()
    }

    // The files of another device.

    pub async fn fs_roots(&self, id: String) -> Result<Vec<TandemFsRoot>, TandemError> {
        let peer = DeviceId::parse(&id)?;
        let engine = self.engine.clone();
        let roots = self.runtime.spawn(async move { engine.files(peer).roots().await }).await.map_err(join_error)??;
        Ok(roots.into_iter().map(|r| TandemFsRoot { name: r.name, write: r.write }).collect())
    }

    pub async fn fs_list(&self, id: String, path: String) -> Result<Vec<TandemFsEntry>, TandemError> {
        let peer = DeviceId::parse(&id)?;
        let engine = self.engine.clone();
        let items = self.runtime.spawn(async move { engine.files(peer).list(&path).await }).await.map_err(join_error)??;
        Ok(items.into_iter().map(Into::into).collect())
    }

    pub async fn fs_stat(&self, id: String, path: String) -> Result<TandemFsEntry, TandemError> {
        let peer = DeviceId::parse(&id)?;
        let engine = self.engine.clone();
        let entry = self.runtime.spawn(async move { engine.files(peer).stat(&path).await }).await.map_err(join_error)??;
        Ok(entry.into())
    }

    /// Part of a file, in memory. At most 64 MiB; for more, download it.
    pub async fn fs_read(&self, id: String, path: String, offset: u64, len: u64) -> Result<Vec<u8>, TandemError> {
        let peer = DeviceId::parse(&id)?;
        let engine = self.engine.clone();
        self.runtime.spawn(async move { engine.files(peer).read(&path, offset, len).await }).await.map_err(join_error)?.map_err(Into::into)
    }

    /// A file of the other device to `to`, a path on this one. What an earlier try left as `to.tandem-part` is carried on.
    pub async fn fs_download(
        &self,
        id: String,
        path: String,
        to: String,
        progress: Option<Arc<dyn TandemFsProgress>>,
    ) -> Result<(), TandemError> {
        let peer = DeviceId::parse(&id)?;
        let engine = self.engine.clone();
        self.runtime
            .spawn(async move {
                engine
                    .files(peer)
                    .download(&path, std::path::Path::new(&to), move |done, total| {
                        if let Some(progress) = &progress {
                            progress.progress(done, total);
                        }
                    })
                    .await
            })
            .await
            .map_err(join_error)?
            .map_err(Into::into)
    }

    /// A file on this device, a path, to the other device.
    pub async fn fs_upload(
        &self,
        id: String,
        from: String,
        path: String,
        overwrite: bool,
        progress: Option<Arc<dyn TandemFsProgress>>,
    ) -> Result<(), TandemError> {
        let peer = DeviceId::parse(&id)?;
        let engine = self.engine.clone();
        self.runtime
            .spawn(async move {
                engine
                    .files(peer)
                    .upload(std::path::Path::new(&from), &path, overwrite, move |done, total| {
                        if let Some(progress) = &progress {
                            progress.progress(done, total);
                        }
                    })
                    .await
            })
            .await
            .map_err(join_error)?
            .map_err(Into::into)
    }

    pub async fn fs_mkdir(&self, id: String, path: String) -> Result<(), TandemError> {
        let peer = DeviceId::parse(&id)?;
        let engine = self.engine.clone();
        self.runtime.spawn(async move { engine.files(peer).mkdir(&path).await }).await.map_err(join_error)?.map_err(Into::into)
    }

    pub async fn fs_remove(&self, id: String, path: String, recursive: bool) -> Result<(), TandemError> {
        let peer = DeviceId::parse(&id)?;
        let engine = self.engine.clone();
        self.runtime.spawn(async move { engine.files(peer).remove(&path, recursive).await }).await.map_err(join_error)?.map_err(Into::into)
    }

    pub async fn fs_rename(&self, id: String, from: String, to: String, overwrite: bool) -> Result<(), TandemError> {
        let peer = DeviceId::parse(&id)?;
        let engine = self.engine.clone();
        self.runtime.spawn(async move { engine.files(peer).rename(&from, &to, overwrite).await }).await.map_err(join_error)?.map_err(Into::into)
    }
}

/// Where the files of a device can be opened as a drive.
#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemWebDav {
    pub url: String,
    pub user: String,
    pub password: String,
}

#[uniffi::export(async_runtime = "tokio")]
impl TandemEngine {
    /// Serves the files of a device as a WebDAV share on this machine, for Finder or Explorer to open as a drive. It
    /// is a new one each time, with a password made for it; the one before is stopped. A build for a phone has no
    /// use for this and says so.
    pub async fn serve_files_as_drive(&self, id: String, name: String) -> Result<TandemWebDav, TandemError> {
        #[cfg(feature = "webdav")]
        {
            let peer = DeviceId::parse(&id)?;
            let engine = self.engine.clone();
            let share = self
                .runtime
                .spawn(async move { crate::webdav::serve(engine.files(peer), &name).await })
                .await
                .map_err(join_error)??;
            let reply = TandemWebDav { url: share.url.clone(), user: share.user.clone(), password: share.password.clone() };
            if let Some(old) = self.drives.lock().unwrap().insert(id, share) {
                old.stop();
            }
            Ok(reply)
        }
        #[cfg(not(feature = "webdav"))]
        {
            let _ = (id, name);
            Err(TandemError::Failed { reason: "this build cannot serve files as a drive".into() })
        }
    }

    /// Stops serving the files of a device as a drive.
    pub fn stop_serving_files_as_drive(&self, id: String) {
        #[cfg(feature = "webdav")]
        if let Some(old) = self.drives.lock().unwrap().remove(&id) {
            old.stop();
        }
        #[cfg(not(feature = "webdav"))]
        let _ = id;
    }
}

// ---- Live video: a screen or a camera, and the control of a screen ----------------------
//
// The contract is in docs/SCREEN.md. Everything here returns at once: the calls that can be made from an encoder or a
// UI thread never wait for the network.

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemMediaKind {
    Screen,
    Camera,
}

impl From<crate::live::MediaKind> for TandemMediaKind {
    fn from(kind: crate::live::MediaKind) -> Self {
        match kind {
            crate::live::MediaKind::Camera => TandemMediaKind::Camera,
            // A kind this version does not know is turned away before an app ever sees it.
            crate::live::MediaKind::Screen | crate::live::MediaKind::Other => TandemMediaKind::Screen,
        }
    }
}

impl From<TandemMediaKind> for crate::live::MediaKind {
    fn from(kind: TandemMediaKind) -> Self {
        match kind {
            TandemMediaKind::Screen => crate::live::MediaKind::Screen,
            TandemMediaKind::Camera => crate::live::MediaKind::Camera,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemMediaCodec {
    H264,
    Hevc,
}

impl From<crate::live::MediaCodec> for TandemMediaCodec {
    fn from(codec: crate::live::MediaCodec) -> Self {
        match codec {
            crate::live::MediaCodec::Hevc => TandemMediaCodec::Hevc,
            crate::live::MediaCodec::H264 | crate::live::MediaCodec::Other => TandemMediaCodec::H264,
        }
    }
}

impl From<TandemMediaCodec> for crate::live::MediaCodec {
    fn from(codec: TandemMediaCodec) -> Self {
        match codec {
            TandemMediaCodec::H264 => crate::live::MediaCodec::H264,
            TandemMediaCodec::Hevc => crate::live::MediaCodec::Hevc,
        }
    }
}

/// Why a session did not start or came to an end.
#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemMediaEnd {
    /// A person stopped it.
    Ended,
    Declined,
    /// The policy of the host says never.
    Policy,
    Busy,
    /// The kind or the codec is not something the host can do.
    Unsupported,
    /// The host would, but cannot: no permission to capture, no camera.
    Unavailable,
    Timeout,
    /// The same device started a new session of this kind.
    Replaced,
    UnknownSession,
    /// The other device was gone for longer than the grace period, or restarted.
    PeerGone,
    Error,
}

impl From<crate::live::MediaEnd> for TandemMediaEnd {
    fn from(end: crate::live::MediaEnd) -> Self {
        use crate::live::MediaEnd as E;
        match end {
            E::Ended => TandemMediaEnd::Ended,
            E::Declined => TandemMediaEnd::Declined,
            E::Policy => TandemMediaEnd::Policy,
            E::Busy => TandemMediaEnd::Busy,
            E::Unsupported => TandemMediaEnd::Unsupported,
            E::Unavailable => TandemMediaEnd::Unavailable,
            E::Timeout => TandemMediaEnd::Timeout,
            E::Replaced => TandemMediaEnd::Replaced,
            E::UnknownSession => TandemMediaEnd::UnknownSession,
            E::PeerGone => TandemMediaEnd::PeerGone,
            E::Error => TandemMediaEnd::Error,
        }
    }
}

impl From<TandemMediaEnd> for crate::live::MediaEnd {
    fn from(end: TandemMediaEnd) -> Self {
        use crate::live::MediaEnd as E;
        match end {
            TandemMediaEnd::Ended => E::Ended,
            TandemMediaEnd::Declined => E::Declined,
            TandemMediaEnd::Policy => E::Policy,
            TandemMediaEnd::Busy => E::Busy,
            TandemMediaEnd::Unsupported => E::Unsupported,
            TandemMediaEnd::Unavailable => E::Unavailable,
            TandemMediaEnd::Timeout => E::Timeout,
            TandemMediaEnd::Replaced => E::Replaced,
            TandemMediaEnd::UnknownSession => E::UnknownSession,
            TandemMediaEnd::PeerGone => E::PeerGone,
            TandemMediaEnd::Error => E::Error,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemMediaFacing {
    Any,
    Front,
    Back,
}

impl From<crate::live::MediaFacing> for TandemMediaFacing {
    fn from(facing: crate::live::MediaFacing) -> Self {
        match facing {
            crate::live::MediaFacing::Any => TandemMediaFacing::Any,
            crate::live::MediaFacing::Front => TandemMediaFacing::Front,
            crate::live::MediaFacing::Back => TandemMediaFacing::Back,
        }
    }
}

impl From<TandemMediaFacing> for crate::live::MediaFacing {
    fn from(facing: TandemMediaFacing) -> Self {
        match facing {
            TandemMediaFacing::Any => crate::live::MediaFacing::Any,
            TandemMediaFacing::Front => crate::live::MediaFacing::Front,
            TandemMediaFacing::Back => crate::live::MediaFacing::Back,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemMediaRole {
    Host,
    Viewer,
}

impl From<crate::live::MediaRole> for TandemMediaRole {
    fn from(role: crate::live::MediaRole) -> Self {
        match role {
            crate::live::MediaRole::Host => TandemMediaRole::Host,
            crate::live::MediaRole::Viewer => TandemMediaRole::Viewer,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemMediaState {
    /// Viewer: the request is out.
    Requesting,
    /// Host: the app is being asked.
    Pending,
    Active,
    /// The connection is gone and may come back within the grace period.
    Suspended,
}

impl From<crate::live::MediaState> for TandemMediaState {
    fn from(state: crate::live::MediaState) -> Self {
        match state {
            crate::live::MediaState::Requesting => TandemMediaState::Requesting,
            crate::live::MediaState::Pending => TandemMediaState::Pending,
            crate::live::MediaState::Active => TandemMediaState::Active,
            crate::live::MediaState::Suspended => TandemMediaState::Suspended,
        }
    }
}

/// What became of a frame the host app pushed.
#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemMediaPush {
    /// Queued for the network. Not a promise that it arrives.
    Sent,
    /// Dropped because the link is behind or the viewer is away. A keyframe is asked for through `on_keyframe`.
    Dropped,
    /// Not a keyframe, and the stream has a hole: nothing goes out until a keyframe comes.
    WaitingForKeyframe,
    /// Refused: empty, too big, not Annex B, or a keyframe without any parameter sets.
    Invalid,
    /// No such session, or it has ended.
    NoSession,
}

impl From<crate::live::MediaPush> for TandemMediaPush {
    fn from(push: crate::live::MediaPush) -> Self {
        match push {
            crate::live::MediaPush::Sent => TandemMediaPush::Sent,
            crate::live::MediaPush::Dropped => TandemMediaPush::Dropped,
            crate::live::MediaPush::WaitingForKeyframe => TandemMediaPush::WaitingForKeyframe,
            crate::live::MediaPush::Invalid => TandemMediaPush::Invalid,
            crate::live::MediaPush::NoSession => TandemMediaPush::NoSession,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum TandemMediaPermission {
    Ask,
    Always,
    Never,
}

impl From<crate::live::MediaPermission> for TandemMediaPermission {
    fn from(permission: crate::live::MediaPermission) -> Self {
        match permission {
            crate::live::MediaPermission::Ask => TandemMediaPermission::Ask,
            crate::live::MediaPermission::Always => TandemMediaPermission::Always,
            crate::live::MediaPermission::Never => TandemMediaPermission::Never,
        }
    }
}

impl From<TandemMediaPermission> for crate::live::MediaPermission {
    fn from(permission: TandemMediaPermission) -> Self {
        match permission {
            TandemMediaPermission::Ask => crate::live::MediaPermission::Ask,
            TandemMediaPermission::Always => crate::live::MediaPermission::Always,
            TandemMediaPermission::Never => crate::live::MediaPermission::Never,
        }
    }
}

/// What one device may ask of this one. See `live::MediaPolicy`.
#[derive(Clone, Copy, Debug, uniffi::Record)]
pub struct TandemMediaPolicy {
    /// Showing this device's screen.
    pub screen: TandemMediaPermission,
    /// Showing this device's camera.
    pub camera: TandemMediaPermission,
    /// Letting the other device control this device's screen.
    pub control: TandemMediaPermission,
}

impl From<crate::live::MediaPolicy> for TandemMediaPolicy {
    fn from(policy: crate::live::MediaPolicy) -> Self {
        TandemMediaPolicy { screen: policy.screen.into(), camera: policy.camera.into(), control: policy.control.into() }
    }
}

impl From<TandemMediaPolicy> for crate::live::MediaPolicy {
    fn from(policy: TandemMediaPolicy) -> Self {
        crate::live::MediaPolicy { screen: policy.screen.into(), camera: policy.camera.into(), control: policy.control.into() }
    }
}

/// What the viewer asks the host for. Zeros mean no preference.
#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemMediaWant {
    pub kind: TandemMediaKind,
    /// Preferred first.
    pub codecs: Vec<TandemMediaCodec>,
    pub max_width: u32,
    pub max_height: u32,
    pub max_fps: u32,
    /// Bits per second.
    pub max_bitrate: u32,
    /// Only means something for a screen.
    pub control: bool,
    pub facing: TandemMediaFacing,
}

/// A request as the host app gets it.
#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemMediaRequest {
    pub session: u64,
    pub kind: TandemMediaKind,
    pub codecs: Vec<TandemMediaCodec>,
    pub max_width: u32,
    pub max_height: u32,
    pub max_fps: u32,
    pub max_bitrate: u32,
    pub control: bool,
    pub facing: TandemMediaFacing,
}

impl From<crate::live::MediaRequest> for TandemMediaRequest {
    fn from(request: crate::live::MediaRequest) -> Self {
        TandemMediaRequest {
            session: request.session,
            kind: request.kind.into(),
            codecs: request.codecs.into_iter().map(Into::into).collect(),
            max_width: request.max_width,
            max_height: request.max_height,
            max_fps: request.max_fps,
            max_bitrate: request.max_bitrate,
            control: request.control,
            facing: request.facing.into(),
        }
    }
}

/// What the host gives, as the host app states it and as the viewer app is told.
#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemMediaAccept {
    pub codec: TandemMediaCodec,
    pub width: u32,
    pub height: u32,
    pub fps: u32,
    /// The starting target in bits per second, and the most the core will ever ask the encoder for.
    pub bitrate: u32,
    /// Whether the viewer may send input. The core clamps it by the request and by the policy.
    pub control: bool,
}

impl From<crate::live::MediaAccept> for TandemMediaAccept {
    fn from(accept: crate::live::MediaAccept) -> Self {
        TandemMediaAccept {
            codec: accept.codec.into(),
            width: accept.width,
            height: accept.height,
            fps: accept.fps,
            bitrate: accept.bitrate,
            control: accept.control,
        }
    }
}

/// The picture changed shape, or control was granted or taken away. Fields that did not change are `None`.
#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemMediaUpdate {
    pub width: Option<u32>,
    pub height: Option<u32>,
    /// Degrees clockwise the picture has to be turned to look upright.
    pub rotation: Option<u16>,
    pub fps: Option<u32>,
    pub control: Option<bool>,
}

impl From<crate::live::MediaUpdate> for TandemMediaUpdate {
    fn from(update: crate::live::MediaUpdate) -> Self {
        TandemMediaUpdate {
            width: update.format.map(|f| f.width),
            height: update.format.map(|f| f.height),
            rotation: update.format.map(|f| f.rotation),
            fps: update.format.map(|f| f.fps),
            control: update.control,
        }
    }
}

impl From<TandemMediaUpdate> for crate::live::MediaUpdate {
    fn from(update: TandemMediaUpdate) -> Self {
        // A size needs both sides; one alone says nothing about the shape.
        let format = match (update.width, update.height) {
            (Some(width), Some(height)) => Some(crate::live::MediaFormat {
                width,
                height,
                rotation: update.rotation.unwrap_or(0),
                fps: update.fps.unwrap_or(0),
            }),
            _ => None,
        };
        crate::live::MediaUpdate { format, control: update.control }
    }
}

#[derive(Clone, Debug, PartialEq, uniffi::Enum)]
pub enum TandemMediaInput {
    /// A fraction of the streamed picture, 0.0 to 1.0, the top left corner is the origin.
    PointerAbs { x: f32, y: f32 },
    PointerRel { dx: i16, dy: i16 },
    /// 0 primary, 1 secondary, 2 middle, 3 back, 4 forward. `clicks` is the count of this press, 0 counts as 1.
    Button { button: u8, down: bool, clicks: u8 },
    /// Pixels of the streamed picture, in the natural direction: the content follows the fingers.
    Scroll { dx: i16, dy: i16 },
    /// `code` is the USB HID usage on the Keyboard page, `mods` is 1 shift, 2 control, 4 alt, 8 meta, 16 caps lock.
    Key { code: u32, down: bool, mods: u16, text: String },
    /// A piece of text that was committed. Not the clipboard.
    Text { text: String },
}

impl From<crate::live::MediaInput> for TandemMediaInput {
    fn from(input: crate::live::MediaInput) -> Self {
        use crate::live::MediaInput as I;
        match input {
            I::PointerAbs { x, y } => TandemMediaInput::PointerAbs { x, y },
            I::PointerRel { dx, dy } => TandemMediaInput::PointerRel { dx, dy },
            I::Button { button, down, clicks } => TandemMediaInput::Button { button, down, clicks },
            I::Scroll { dx, dy } => TandemMediaInput::Scroll { dx, dy },
            I::Key { code, down, mods, text } => TandemMediaInput::Key { code, down, mods, text },
            I::Text { text } => TandemMediaInput::Text { text },
        }
    }
}

impl From<TandemMediaInput> for crate::live::MediaInput {
    fn from(input: TandemMediaInput) -> Self {
        use crate::live::MediaInput as I;
        match input {
            TandemMediaInput::PointerAbs { x, y } => I::PointerAbs { x, y },
            TandemMediaInput::PointerRel { dx, dy } => I::PointerRel { dx, dy },
            TandemMediaInput::Button { button, down, clicks } => I::Button { button, down, clicks },
            TandemMediaInput::Scroll { dx, dy } => I::Scroll { dx, dy },
            TandemMediaInput::Key { code, down, mods, text } => I::Key { code, down, mods, text },
            TandemMediaInput::Text { text } => I::Text { text },
        }
    }
}

/// A live session as the apps list it.
#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemMediaSession {
    pub session: u64,
    pub peer: String,
    pub kind: TandemMediaKind,
    pub role: TandemMediaRole,
    pub state: TandemMediaState,
    pub accept: Option<TandemMediaAccept>,
    pub control: bool,
}

/// Counters of a session, for a debug overlay. What does not apply to the role stays zero.
#[derive(Clone, Debug, uniffi::Record)]
pub struct TandemMediaStats {
    /// Host: frames the app pushed. Viewer: frames that arrived whole.
    pub frames_in: u64,
    /// Host: frames queued for the network. Viewer: frames handed to the app.
    pub frames_out: u64,
    /// Host: bytes queued. Viewer: bytes received.
    pub bytes: u64,
    pub dropped_busy: u64,
    pub dropped_late: u64,
    pub dropped_waiting: u64,
    pub dropped_invalid: u64,
    pub dropped_offline: u64,
    pub superseded: u64,
    pub lost: u64,
    pub discarded: u64,
    pub late: u64,
    pub app_dropped: u64,
    pub keyframes_requested: u64,
    pub input_refused: u64,
    pub target_bitrate: u32,
    pub inflight_frames: u32,
    pub inflight_bytes: u64,
    pub jitter_us: u32,
    pub last_frame_age_ms: Option<u64>,
    pub rtt_ms: Option<u32>,
}

impl From<crate::live::MediaStats> for TandemMediaStats {
    fn from(s: crate::live::MediaStats) -> Self {
        TandemMediaStats {
            frames_in: s.frames_in,
            frames_out: s.frames_out,
            bytes: s.bytes,
            dropped_busy: s.dropped_busy,
            dropped_late: s.dropped_late,
            dropped_waiting: s.dropped_waiting,
            dropped_invalid: s.dropped_invalid,
            dropped_offline: s.dropped_offline,
            superseded: s.superseded,
            lost: s.lost,
            discarded: s.discarded,
            late: s.late,
            app_dropped: s.app_dropped,
            keyframes_requested: s.keyframes_requested,
            input_refused: s.input_refused,
            target_bitrate: s.target_bitrate,
            inflight_frames: s.inflight_frames,
            inflight_bytes: s.inflight_bytes,
            jitter_us: s.jitter_us,
            last_frame_age_ms: s.last_frame_age_ms,
            rtt_ms: s.rtt_ms,
        }
    }
}

/// The app that has the picture. Every method is called on a thread of the core and must only note what happened and
/// return. `on_stop` can overlap in time with another callback; after it nothing more is wanted for the session.
#[uniffi::export(foreign)]
pub trait TandemMediaHost: Send + Sync {
    /// Another device asks for the screen or the camera. `pre_approved` means the person said "always" for this device
    /// and kind: do not ask again, but do start the capture and call `media_accept`.
    fn on_request(&self, from: String, request: TandemMediaRequest, pre_approved: bool);
    /// The viewer needs a keyframe now: force one out of the encoder.
    fn on_keyframe(&self, session: u64);
    /// The link carries less (or more) than before: move the encoder to this many bits per second.
    fn on_bitrate(&self, session: u64, bits_per_second: u32);
    /// Input from the viewer. Only comes when control was granted.
    fn on_input(&self, session: u64, input: TandemMediaInput);
    /// The session is over, for whatever reason, including a stop by this very app.
    fn on_stop(&self, session: u64, reason: TandemMediaEnd);
}

/// The app that shows the picture. `on_frame` is called one frame at a time, in order, from a task of the session's own;
/// `on_ended` is always the last call for a session. Queue the frames to the decoder and return.
#[uniffi::export(foreign)]
pub trait TandemMediaViewer: Send + Sync {
    fn on_accepted(&self, session: u64, accept: TandemMediaAccept);
    fn on_update(&self, session: u64, update: TandemMediaUpdate);
    /// `data` is one access unit in Annex B; a keyframe starts with its parameter sets. When `discontinuity` is set, flush
    /// the decoder before this frame.
    fn on_frame(&self, session: u64, pts_us: u64, keyframe: bool, discontinuity: bool, data: Vec<u8>);
    fn on_ended(&self, session: u64, reason: TandemMediaEnd);
}

struct MediaHostAdapter(Arc<dyn TandemMediaHost>);

impl crate::live::MediaHost for MediaHostAdapter {
    fn on_request(&self, from: DeviceId, request: crate::live::MediaRequest, pre_approved: bool) {
        self.0.on_request(from.to_string(), request.into(), pre_approved);
    }

    fn on_keyframe(&self, session: u64) {
        self.0.on_keyframe(session);
    }

    fn on_bitrate(&self, session: u64, bits_per_second: u32) {
        self.0.on_bitrate(session, bits_per_second);
    }

    fn on_input(&self, session: u64, input: crate::live::MediaInput) {
        self.0.on_input(session, input.into());
    }

    fn on_stop(&self, session: u64, reason: crate::live::MediaEnd) {
        self.0.on_stop(session, reason.into());
    }
}

struct MediaViewerAdapter(Arc<dyn TandemMediaViewer>);

impl crate::live::MediaViewer for MediaViewerAdapter {
    fn on_accepted(&self, session: u64, accept: crate::live::MediaAccept) {
        self.0.on_accepted(session, accept.into());
    }

    fn on_update(&self, session: u64, update: crate::live::MediaUpdate) {
        self.0.on_update(session, update.into());
    }

    fn on_frame(&self, session: u64, frame: crate::live::MediaFrame) {
        self.0.on_frame(session, frame.pts_us, frame.keyframe, frame.discontinuity, frame.data);
    }

    fn on_ended(&self, session: u64, reason: crate::live::MediaEnd) {
        self.0.on_ended(session, reason.into());
    }
}

#[uniffi::export]
impl TandemEngine {
    /// Where requests for this device's screen or camera, keyframe requests, bitrate hints and input go. Set it before
    /// anyone can ask: without one, every request is answered with `Unsupported`.
    pub fn set_media_host(&self, host: Arc<dyn TandemMediaHost>) {
        self.engine.set_media_host(Arc::new(MediaHostAdapter(host)));
    }

    /// Where the frames of the sessions this device asks for go.
    pub fn set_media_viewer(&self, viewer: Arc<dyn TandemMediaViewer>) {
        self.engine.set_media_viewer(Arc::new(MediaViewerAdapter(viewer)));
    }

    /// Asks a device for its screen or camera. Returns the session id at once; the answer arrives through
    /// `TandemMediaViewer.on_accepted` or `on_ended`.
    pub fn media_request(&self, peer: String, want: TandemMediaWant) -> Result<u64, TandemError> {
        let peer = DeviceId::parse(&peer)?;
        let mut request = crate::live::MediaWant::new(want.kind.into());
        request.codecs = want.codecs.into_iter().map(Into::into).collect();
        request.max_width = want.max_width;
        request.max_height = want.max_height;
        request.max_fps = want.max_fps;
        request.max_bitrate = want.max_bitrate;
        request.control = want.control;
        request.facing = want.facing.into();
        self.engine.media_request(peer, request).map_err(Into::into)
    }

    /// The host app agrees. Frames may be pushed from now on; the first one must be a keyframe.
    pub fn media_accept(&self, session: u64, answer: TandemMediaAccept) -> Result<(), TandemError> {
        let answer = crate::live::MediaAnswer {
            codec: answer.codec.into(),
            width: answer.width,
            height: answer.height,
            fps: answer.fps,
            bitrate: answer.bitrate,
            control: answer.control,
        };
        self.engine.media_accept(session, answer).map_err(Into::into)
    }

    pub fn media_deny(&self, session: u64, reason: TandemMediaEnd) -> Result<(), TandemError> {
        self.engine.media_deny(session, reason.into()).map_err(Into::into)
    }

    /// Ends a session from either side. The other side is told.
    pub fn media_stop(&self, session: u64) -> Result<(), TandemError> {
        self.engine.media_stop(session).map_err(Into::into)
    }

    /// An encoded frame: one access unit in Annex B. Never waits for the network; the answer says what became of it.
    pub fn media_push_frame(&self, session: u64, data: Vec<u8>, pts_us: u64, keyframe: bool) -> TandemMediaPush {
        self.engine.media_push_frame(session, data, pts_us, keyframe).into()
    }

    /// Parameter sets the encoder gave apart from its frames (SPS and PPS, and VPS for HEVC), in Annex B. They are put
    /// in front of every keyframe that comes without them.
    pub fn media_push_config(&self, session: u64, data: Vec<u8>) -> Result<(), TandemError> {
        self.engine.media_push_config(session, data).map_err(Into::into)
    }

    /// The picture changed shape, or control is granted or taken away. Call it before the first frame of the new size;
    /// that frame must be a keyframe.
    pub fn media_update(&self, session: u64, update: TandemMediaUpdate) -> Result<(), TandemError> {
        self.engine.media_update(session, update.into()).map_err(Into::into)
    }

    /// Input for the host. Fails when control was not granted.
    pub fn media_send_input(&self, session: u64, input: TandemMediaInput) -> Result<(), TandemError> {
        self.engine.media_send_input(session, input.into()).map_err(Into::into)
    }

    /// The decoder choked: ask the host for a keyframe.
    pub fn media_request_keyframe(&self, session: u64) -> Result<(), TandemError> {
        self.engine.media_request_keyframe(session).map_err(Into::into)
    }

    pub fn media_sessions(&self) -> Vec<TandemMediaSession> {
        self.engine
            .media_sessions()
            .into_iter()
            .map(|s| TandemMediaSession {
                session: s.session,
                peer: s.peer.to_string(),
                kind: s.kind.into(),
                role: s.role.into(),
                state: s.state.into(),
                accept: s.accept.map(Into::into),
                control: s.control,
            })
            .collect()
    }

    pub fn media_stats(&self, session: u64) -> Option<TandemMediaStats> {
        self.engine.media_stats(session).map(Into::into)
    }

    // What other devices may ask of this one.

    pub fn media_policy(&self, id: String) -> Result<TandemMediaPolicy, TandemError> {
        Ok(self.engine.media_policy(&DeviceId::parse(&id)?).into())
    }

    /// Whether the device has choices of its own, or is on the default.
    pub fn has_own_media_policy(&self, id: String) -> bool {
        DeviceId::parse(&id).map(|id| self.engine.has_own_media_policy(&id)).unwrap_or(false)
    }

    pub fn media_default_policy(&self) -> TandemMediaPolicy {
        self.engine.media_default_policy().into()
    }

    pub fn set_media_policy(&self, id: String, policy: TandemMediaPolicy) -> Result<(), TandemError> {
        self.engine.set_media_policy(&DeviceId::parse(&id)?, policy.into()).map_err(Into::into)
    }

    /// Back to the default for this device.
    pub fn clear_media_policy(&self, id: String) -> Result<(), TandemError> {
        self.engine.clear_media_policy(&DeviceId::parse(&id)?).map_err(Into::into)
    }

    pub fn set_media_default_policy(&self, policy: TandemMediaPolicy) -> Result<(), TandemError> {
        self.engine.set_media_default_policy(policy.into()).map_err(Into::into)
    }
}
